package mnj.ont.model.lov.views;

import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed May 06 12:25:22 PKT 2015
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class CutJobIdLovRowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. Do not modify.
     */
    public enum AttributesEnum {
        WipEntityId {
            public Object get(CutJobIdLovRowImpl obj) {
                return obj.getWipEntityId();
            }

            public void put(CutJobIdLovRowImpl obj, Object value) {
                obj.setWipEntityId((Number)value);
            }
        }
        ,
        WipEntityName {
            public Object get(CutJobIdLovRowImpl obj) {
                return obj.getWipEntityName();
            }

            public void put(CutJobIdLovRowImpl obj, Object value) {
                obj.setWipEntityName((String)value);
            }
        }
        ,
        RationPlanId {
            public Object get(CutJobIdLovRowImpl obj) {
                return obj.getRationPlanId();
            }

            public void put(CutJobIdLovRowImpl obj, Object value) {
                obj.setRationPlanId((String)value);
            }
        }
        ,
        StartQuantity {
            public Object get(CutJobIdLovRowImpl obj) {
                return obj.getStartQuantity();
            }

            public void put(CutJobIdLovRowImpl obj, Object value) {
                obj.setStartQuantity((Number)value);
            }
        }
        ,
        NetQuantity {
            public Object get(CutJobIdLovRowImpl obj) {
                return obj.getNetQuantity();
            }

            public void put(CutJobIdLovRowImpl obj, Object value) {
                obj.setNetQuantity((Number)value);
            }
        }
        ,
        PreviousQty {
            public Object get(CutJobIdLovRowImpl obj) {
                return obj.getPreviousQty();
            }

            public void put(CutJobIdLovRowImpl obj, Object value) {
                obj.setPreviousQty((Number)value);
            }
        }
        ,
        BelanceQuantity {
            public Object get(CutJobIdLovRowImpl obj) {
                return obj.getBelanceQuantity();
            }

            public void put(CutJobIdLovRowImpl obj, Object value) {
                obj.setBelanceQuantity((Number)value);
            }
        }
        ,
        OrganizationId {
            public Object get(CutJobIdLovRowImpl obj) {
                return obj.getOrganizationId();
            }

            public void put(CutJobIdLovRowImpl obj, Object value) {
                obj.setOrganizationId((Number)value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static int firstIndex = 0;

        public abstract Object get(CutJobIdLovRowImpl object);

        public abstract void put(CutJobIdLovRowImpl object, Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int WIPENTITYID = AttributesEnum.WipEntityId.index();
    public static final int WIPENTITYNAME = AttributesEnum.WipEntityName.index();
    public static final int RATIONPLANID = AttributesEnum.RationPlanId.index();
    public static final int STARTQUANTITY = AttributesEnum.StartQuantity.index();
    public static final int NETQUANTITY = AttributesEnum.NetQuantity.index();
    public static final int PREVIOUSQTY = AttributesEnum.PreviousQty.index();
    public static final int BELANCEQUANTITY = AttributesEnum.BelanceQuantity.index();
    public static final int ORGANIZATIONID = AttributesEnum.OrganizationId.index();

    /**
     * This is the default constructor (do not remove).
     */
    public CutJobIdLovRowImpl() {
    }

    /**
     * Gets the attribute value for the calculated attribute WipEntityName.
     * @return the WipEntityName
     */
    public String getWipEntityName() {
        return (String) getAttributeInternal(WIPENTITYNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute WipEntityName.
     * @param value value to set the  WipEntityName
     */
    public void setWipEntityName(String value) {
        setAttributeInternal(WIPENTITYNAME, value);
    }

    /**
     * Gets the attribute value for the calculated attribute RationPlanId.
     * @return the RationPlanId
     */
    public String getRationPlanId() {
        return (String) getAttributeInternal(RATIONPLANID);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute RationPlanId.
     * @param value value to set the  RationPlanId
     */
    public void setRationPlanId(String value) {
        setAttributeInternal(RATIONPLANID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute StartQuantity.
     * @return the StartQuantity
     */
    public Number getStartQuantity() {
        return (Number) getAttributeInternal(STARTQUANTITY);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute StartQuantity.
     * @param value value to set the  StartQuantity
     */
    public void setStartQuantity(Number value) {
        setAttributeInternal(STARTQUANTITY, value);
    }

    /**
     * Gets the attribute value for the calculated attribute NetQuantity.
     * @return the NetQuantity
     */
    public Number getNetQuantity() {
        return (Number) getAttributeInternal(NETQUANTITY);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute NetQuantity.
     * @param value value to set the  NetQuantity
     */
    public void setNetQuantity(Number value) {
        setAttributeInternal(NETQUANTITY, value);
    }

    /**
     * Gets the attribute value for the calculated attribute PreviousQty.
     * @return the PreviousQty
     */
    public Number getPreviousQty() {
        return (Number) getAttributeInternal(PREVIOUSQTY);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute PreviousQty.
     * @param value value to set the  PreviousQty
     */
    public void setPreviousQty(Number value) {
        setAttributeInternal(PREVIOUSQTY, value);
    }

    /**
     * Gets the attribute value for the calculated attribute BelanceQuantity.
     * @return the BelanceQuantity
     */
    public Number getBelanceQuantity() {
        return (Number) getAttributeInternal(BELANCEQUANTITY);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute BelanceQuantity.
     * @param value value to set the  BelanceQuantity
     */
    public void setBelanceQuantity(Number value) {
        setAttributeInternal(BELANCEQUANTITY, value);
    }

    /**
     * Gets the attribute value for the calculated attribute WipEntityId.
     * @return the WipEntityId
     */
    public Number getWipEntityId() {
        return (Number) getAttributeInternal(WIPENTITYID);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute WipEntityId.
     * @param value value to set the  WipEntityId
     */
    public void setWipEntityId(Number value) {
        setAttributeInternal(WIPENTITYID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute OrganizationId.
     * @return the OrganizationId
     */
    public Number getOrganizationId() {
        return (Number) getAttributeInternal(ORGANIZATIONID);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute OrganizationId.
     * @param value value to set the  OrganizationId
     */
    public void setOrganizationId(Number value) {
        setAttributeInternal(ORGANIZATIONID, value);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }
}
