package mnj.ont.model.lov.views;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed May 06 12:25:22 PKT 2015
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class CutJobIdLovImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public CutJobIdLovImpl() {
    }

    /**
     * Returns the variable value for Job_Name.
     * @return variable value for Job_Name
     */
    public String getJob_Name() {
        return (String)ensureVariableManager().getVariableValue("Job_Name");
    }

    /**
     * Sets <code>value</code> for variable Job_Name.
     * @param value value to bind as Job_Name
     */
    public void setJob_Name(String value) {
        ensureVariableManager().setVariableValue("Job_Name", value);
    }

    /**
     * Returns the bind variable value for p_ratioID.
     * @return bind variable value for p_ratioID
     */
    public String getp_ratioID() {
        return (String)getNamedWhereClauseParam("p_ratioID");
    }

    /**
     * Sets <code>value</code> for bind variable p_ratioID.
     * @param value value to bind as p_ratioID
     */
    public void setp_ratioID(String value) {
        setNamedWhereClauseParam("p_ratioID", value);
    }

    /**
     * Returns the bind variable value for p_org_id.
     * @return bind variable value for p_org_id
     */
    public String getp_org_id() {
        return (String)getNamedWhereClauseParam("p_org_id");
    }

    /**
     * Sets <code>value</code> for bind variable p_org_id.
     * @param value value to bind as p_org_id
     */
    public void setp_org_id(String value) {
        setNamedWhereClauseParam("p_org_id", value);
    }
}
