package mnj.ont.model.lov.views;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Feb 18 19:23:22 PKT 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class CutNumberLOVImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public CutNumberLOVImpl() {
    }

    /**
     * Returns the bind variable value for ratioplan_number.
     * @return bind variable value for ratioplan_number
     */
    public String getratioplan_number() {
        return (String)getNamedWhereClauseParam("ratioplan_number");
    }

    /**
     * Sets <code>value</code> for bind variable ratioplan_number.
     * @param value value to bind as ratioplan_number
     */
    public void setratioplan_number(String value) {
        setNamedWhereClauseParam("ratioplan_number", value);
    }

    /**
     * Returns the bind variable value for p_org_id.
     * @return bind variable value for p_org_id
     */
    public String getp_org_id() {
        return (String)getNamedWhereClauseParam("p_org_id");
    }

    /**
     * Sets <code>value</code> for bind variable p_org_id.
     * @param value value to bind as p_org_id
     */
    public void setp_org_id(String value) {
        setNamedWhereClauseParam("p_org_id", value);
    }
}
