package mnj.ont.model.lov.views;

import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu May 28 18:05:46 PKT 2015
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class locaterLOVRowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. Do not modify.
     */
    public enum AttributesEnum {
        PoNumber {
            public Object get(locaterLOVRowImpl obj) {
                return obj.getPoNumber();
            }

            public void put(locaterLOVRowImpl obj, Object value) {
                obj.setPoNumber((String)value);
            }
        }
        ,
        PoSubinventoryCode {
            public Object get(locaterLOVRowImpl obj) {
                return obj.getPoSubinventoryCode();
            }

            public void put(locaterLOVRowImpl obj, Object value) {
                obj.setPoSubinventoryCode((String)value);
            }
        }
        ,
        PoLocatorSegment {
            public Object get(locaterLOVRowImpl obj) {
                return obj.getPoLocatorSegment();
            }

            public void put(locaterLOVRowImpl obj, Object value) {
                obj.setPoLocatorSegment((String)value);
            }
        }
        ,
        PoLotNumber {
            public Object get(locaterLOVRowImpl obj) {
                return obj.getPoLotNumber();
            }

            public void put(locaterLOVRowImpl obj, Object value) {
                obj.setPoLotNumber((String)value);
            }
        }
        ,
        OnHandQty {
            public Object get(locaterLOVRowImpl obj) {
                return obj.getOnHandQty();
            }

            public void put(locaterLOVRowImpl obj, Object value) {
                obj.setOnHandQty((Number)value);
            }
        }
        ,
        LotNumber {
            public Object get(locaterLOVRowImpl obj) {
                return obj.getLotNumber();
            }

            public void put(locaterLOVRowImpl obj, Object value) {
                obj.setLotNumber((String)value);
            }
        }
        ,
        PrimaryUomCode {
            public Object get(locaterLOVRowImpl obj) {
                return obj.getPrimaryUomCode();
            }

            public void put(locaterLOVRowImpl obj, Object value) {
                obj.setPrimaryUomCode((String)value);
            }
        }
        ,
        LocatorId {
            public Object get(locaterLOVRowImpl obj) {
                return obj.getLocatorId();
            }

            public void put(locaterLOVRowImpl obj, Object value) {
                obj.setLocatorId((Number)value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static int firstIndex = 0;

        public abstract Object get(locaterLOVRowImpl object);

        public abstract void put(locaterLOVRowImpl object, Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int PONUMBER = AttributesEnum.PoNumber.index();
    public static final int POSUBINVENTORYCODE = AttributesEnum.PoSubinventoryCode.index();
    public static final int POLOCATORSEGMENT = AttributesEnum.PoLocatorSegment.index();
    public static final int POLOTNUMBER = AttributesEnum.PoLotNumber.index();
    public static final int ONHANDQTY = AttributesEnum.OnHandQty.index();
    public static final int LOTNUMBER = AttributesEnum.LotNumber.index();
    public static final int PRIMARYUOMCODE = AttributesEnum.PrimaryUomCode.index();
    public static final int LOCATORID = AttributesEnum.LocatorId.index();

    /**
     * This is the default constructor (do not remove).
     */
    public locaterLOVRowImpl() {
    }

    /**
     * Gets the attribute value for the calculated attribute PoNumber.
     * @return the PoNumber
     */
    public String getPoNumber() {
        return (String) getAttributeInternal(PONUMBER);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute PoNumber.
     * @param value value to set the  PoNumber
     */
    public void setPoNumber(String value) {
        setAttributeInternal(PONUMBER, value);
    }

    /**
     * Gets the attribute value for the calculated attribute PoSubinventoryCode.
     * @return the PoSubinventoryCode
     */
    public String getPoSubinventoryCode() {
        return (String) getAttributeInternal(POSUBINVENTORYCODE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute PoSubinventoryCode.
     * @param value value to set the  PoSubinventoryCode
     */
    public void setPoSubinventoryCode(String value) {
        setAttributeInternal(POSUBINVENTORYCODE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute PoLocatorSegment.
     * @return the PoLocatorSegment
     */
    public String getPoLocatorSegment() {
        return (String) getAttributeInternal(POLOCATORSEGMENT);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute PoLocatorSegment.
     * @param value value to set the  PoLocatorSegment
     */
    public void setPoLocatorSegment(String value) {
        setAttributeInternal(POLOCATORSEGMENT, value);
    }

    /**
     * Gets the attribute value for the calculated attribute PoLotNumber.
     * @return the PoLotNumber
     */
    public String getPoLotNumber() {
        return (String) getAttributeInternal(POLOTNUMBER);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute PoLotNumber.
     * @param value value to set the  PoLotNumber
     */
    public void setPoLotNumber(String value) {
        setAttributeInternal(POLOTNUMBER, value);
    }

    /**
     * Gets the attribute value for the calculated attribute OnHandQty.
     * @return the OnHandQty
     */
    public Number getOnHandQty() {
        return (Number) getAttributeInternal(ONHANDQTY);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute OnHandQty.
     * @param value value to set the  OnHandQty
     */
    public void setOnHandQty(Number value) {
        setAttributeInternal(ONHANDQTY, value);
    }

    /**
     * Gets the attribute value for the calculated attribute LotNumber.
     * @return the LotNumber
     */
    public String getLotNumber() {
        return (String) getAttributeInternal(LOTNUMBER);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute LotNumber.
     * @param value value to set the  LotNumber
     */
    public void setLotNumber(String value) {
        setAttributeInternal(LOTNUMBER, value);
    }

    /**
     * Gets the attribute value for the calculated attribute PrimaryUomCode.
     * @return the PrimaryUomCode
     */
    public String getPrimaryUomCode() {
        return (String) getAttributeInternal(PRIMARYUOMCODE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute PrimaryUomCode.
     * @param value value to set the  PrimaryUomCode
     */
    public void setPrimaryUomCode(String value) {
        setAttributeInternal(PRIMARYUOMCODE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute LocatorId.
     * @return the LocatorId
     */
    public Number getLocatorId() {
        return (Number) getAttributeInternal(LOCATORID);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute LocatorId.
     * @param value value to set the  LocatorId
     */
    public void setLocatorId(Number value) {
        setAttributeInternal(LOCATORID, value);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }
}
