package mnj.ont.model.lov.views;

import oracle.jbo.domain.Number;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sat Jun 27 11:09:43 PKT 2015
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class LovCutVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public LovCutVOImpl() {
    }


    /**
     * Returns the variable value for p_cutNo.
     * @return variable value for p_cutNo
     */
    public String getp_cutNo() {
        return (String)ensureVariableManager().getVariableValue("p_cutNo");
    }

    /**
     * Sets <code>value</code> for variable p_cutNo.
     * @param value value to bind as p_cutNo
     */
    public void setp_cutNo(String value) {
        ensureVariableManager().setVariableValue("p_cutNo", value);
    }

    /**
     * Returns the variable value for p_pationplnId.
     * @return variable value for p_pationplnId
     */
    public Number getp_pationplnId() {
        return (Number)ensureVariableManager().getVariableValue("p_pationplnId");
    }

    /**
     * Sets <code>value</code> for variable p_pationplnId.
     * @param value value to bind as p_pationplnId
     */
    public void setp_pationplnId(Number value) {
        ensureVariableManager().setVariableValue("p_pationplnId", value);
    }

    /**
     * Returns the bind variable value for p_org_id.
     * @return bind variable value for p_org_id
     */
    public String getp_org_id() {
        return (String)getNamedWhereClauseParam("p_org_id");
    }

    /**
     * Sets <code>value</code> for bind variable p_org_id.
     * @param value value to bind as p_org_id
     */
    public void setp_org_id(String value) {
        setNamedWhereClauseParam("p_org_id", value);
    }
}
