package mnj.ont.model.lov.views;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Feb 18 18:56:58 PKT 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class PlanNOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public PlanNOImpl() {
    }

    /**
     * Returns the bind variable value for p_buyerId.
     * @return bind variable value for p_buyerId
     */
    public String getp_buyerId() {
        return (String)getNamedWhereClauseParam("p_buyerId");
    }

    /**
     * Sets <code>value</code> for bind variable p_buyerId.
     * @param value value to bind as p_buyerId
     */
    public void setp_buyerId(String value) {
        setNamedWhereClauseParam("p_buyerId", value);
    }

    /**
     * Returns the bind variable value for p_org_id.
     * @return bind variable value for p_org_id
     */
    public String getp_org_id() {
        return (String)getNamedWhereClauseParam("p_org_id");
    }

    /**
     * Sets <code>value</code> for bind variable p_org_id.
     * @param value value to bind as p_org_id
     */
    public void setp_org_id(String value) {
        setNamedWhereClauseParam("p_org_id", value);
    }
}
