package mnj.ont.model.lov.views;

import oracle.jbo.domain.Number;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu May 28 17:49:50 PKT 2015
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class RatioPlanNOLOVImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public RatioPlanNOLOVImpl() {
    }

    /**
     * Returns the variable value for Ratio_number.
     * @return variable value for Ratio_number
     */
    public String getRatio_number() {
        return (String)ensureVariableManager().getVariableValue("Ratio_number");
    }

    /**
     * Sets <code>value</code> for variable Ratio_number.
     * @param value value to bind as Ratio_number
     */
    public void setRatio_number(String value) {
        ensureVariableManager().setVariableValue("Ratio_number", value);
    }


    /**
     * Returns the bind variable value for p_org_id.
     * @return bind variable value for p_org_id
     */
    public String getp_org_id() {
        return (String)getNamedWhereClauseParam("p_org_id");
    }

    /**
     * Sets <code>value</code> for bind variable p_org_id.
     * @param value value to bind as p_org_id
     */
    public void setp_org_id(String value) {
        setNamedWhereClauseParam("p_org_id", value);
    }
}
