package mnj.ont.model.lov.views;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu May 28 16:20:12 PKT 2015
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class RatioPlanLOVImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public RatioPlanLOVImpl() {
    }
}
