package mnj.ont.model.services.client;

import mnj.ont.model.services.common.CuttingProductionAM;

import oracle.jbo.client.remote.ApplicationModuleImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Jun 29 12:05:24 PKT 2015
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class CuttingProductionAMClient extends ApplicationModuleImpl implements CuttingProductionAM {
    /**
     * This is the default constructor (do not remove).
     */
    public CuttingProductionAMClient() {
    }


    public String IssueToFloor(int rangeId) {
        Object _ret =
            this.riInvokeExportedMethod(this,"IssueToFloor",new String [] {"int"},new Object[] {new Integer(rangeId)});
        return (String)_ret;
    }

    public String callPost(int rangeId) {
        Object _ret =
            this.riInvokeExportedMethod(this,"callPost",new String [] {"int"},new Object[] {new Integer(rangeId)});
        return (String)_ret;
    }

    public String submitCompletion(int rangeId) {
        Object _ret =
            this.riInvokeExportedMethod(this,"submitCompletion",new String [] {"int"},new Object[] {new Integer(rangeId)});
        return (String)_ret;
    }

    public void populateOrderLines1(String style) {
        Object _ret =
            this.riInvokeExportedMethod(this,"populateOrderLines1",new String [] {"java.lang.String"},new Object[] {style});
        return;
    }

    public void findSelLines1() {
        Object _ret = this.riInvokeExportedMethod(this,"findSelLines1",null,null);
        return;
    }

    public void TotalCutPlanQuantity() {
        Object _ret =
            this.riInvokeExportedMethod(this,"TotalCutPlanQuantity",null,null);
        return;
    }

    public void setSessionValues(String orgId, String userId, String respId,
                                 String respAppl) {
        Object _ret =
            this.riInvokeExportedMethod(this,"setSessionValues",new String [] {"java.lang.String","java.lang.String","java.lang.String","java.lang.String"},new Object[] {orgId, userId, respId, respAppl});
        return;
    }

    public void CuttingProductionAssignment() {
        Object _ret =
            this.riInvokeExportedMethod(this,"CuttingProductionAssignment",null,null);
        return;
    }
}
