package mnj.ont.model.entities;

import oracle.jbo.AttributeList;
import oracle.jbo.Key;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Mar 26 13:29:50 PKT 2015
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class BundleEOImpl extends EntityImpl {
    private static EntityDefImpl mDefinitionObject;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. Do not modify.
     */
    public enum AttributesEnum {
        DivisionId {
            public Object get(BundleEOImpl obj) {
                return obj.getDivisionId();
            }

            public void put(BundleEOImpl obj, Object value) {
                obj.setDivisionId((String)value);
            }
        }
        ,
        RangeId {
            public Object get(BundleEOImpl obj) {
                return obj.getRangeId();
            }

            public void put(BundleEOImpl obj, Object value) {
                obj.setRangeId((Number)value);
            }
        }
        ,
        RangebndlineId {
            public Object get(BundleEOImpl obj) {
                return obj.getRangebndlineId();
            }

            public void put(BundleEOImpl obj, Object value) {
                obj.setRangebndlineId((Number)value);
            }
        }
        ,
        RangeoblineId {
            public Object get(BundleEOImpl obj) {
                return obj.getRangeoblineId();
            }

            public void put(BundleEOImpl obj, Object value) {
                obj.setRangeoblineId((Number)value);
            }
        }
        ,
        SalesorderId {
            public Object get(BundleEOImpl obj) {
                return obj.getSalesorderId();
            }

            public void put(BundleEOImpl obj, Object value) {
                obj.setSalesorderId((String)value);
            }
        }
        ,
        Shade {
            public Object get(BundleEOImpl obj) {
                return obj.getShade();
            }

            public void put(BundleEOImpl obj, Object value) {
                obj.setShade((String)value);
            }
        }
        ,
        BandelId {
            public Object get(BundleEOImpl obj) {
                return obj.getBandelId();
            }

            public void put(BundleEOImpl obj, Object value) {
                obj.setBandelId((String)value);
            }
        }
        ,
        Plyfrom {
            public Object get(BundleEOImpl obj) {
                return obj.getPlyfrom();
            }

            public void put(BundleEOImpl obj, Object value) {
                obj.setPlyfrom((Number)value);
            }
        }
        ,
        Plyto {
            public Object get(BundleEOImpl obj) {
                return obj.getPlyto();
            }

            public void put(BundleEOImpl obj, Object value) {
                obj.setPlyto((Number)value);
            }
        }
        ,
        Cuttingqty {
            public Object get(BundleEOImpl obj) {
                return obj.getCuttingqty();
            }

            public void put(BundleEOImpl obj, Object value) {
                obj.setCuttingqty((Number)value);
            }
        }
        ,
        FabCons {
            public Object get(BundleEOImpl obj) {
                return obj.getFabCons();
            }

            public void put(BundleEOImpl obj, Object value) {
                obj.setFabCons((Number)value);
            }
        }
        ,
        LastUpdateDate {
            public Object get(BundleEOImpl obj) {
                return obj.getLastUpdateDate();
            }

            public void put(BundleEOImpl obj, Object value) {
                obj.setLastUpdateDate((Date)value);
            }
        }
        ,
        LastUpdatedBy {
            public Object get(BundleEOImpl obj) {
                return obj.getLastUpdatedBy();
            }

            public void put(BundleEOImpl obj, Object value) {
                obj.setLastUpdatedBy((Number)value);
            }
        }
        ,
        CreationDate {
            public Object get(BundleEOImpl obj) {
                return obj.getCreationDate();
            }

            public void put(BundleEOImpl obj, Object value) {
                obj.setCreationDate((Date)value);
            }
        }
        ,
        CreatedBy {
            public Object get(BundleEOImpl obj) {
                return obj.getCreatedBy();
            }

            public void put(BundleEOImpl obj, Object value) {
                obj.setCreatedBy((Number)value);
            }
        }
        ,
        DetailEO {
            public Object get(BundleEOImpl obj) {
                return obj.getDetailEO();
            }

            public void put(BundleEOImpl obj, Object value) {
                obj.setDetailEO((DetailEOImpl)value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static int firstIndex = 0;

        public abstract Object get(BundleEOImpl object);

        public abstract void put(BundleEOImpl object, Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int DIVISIONID = AttributesEnum.DivisionId.index();
    public static final int RANGEID = AttributesEnum.RangeId.index();
    public static final int RANGEBNDLINEID = AttributesEnum.RangebndlineId.index();
    public static final int RANGEOBLINEID = AttributesEnum.RangeoblineId.index();
    public static final int SALESORDERID = AttributesEnum.SalesorderId.index();
    public static final int SHADE = AttributesEnum.Shade.index();
    public static final int BANDELID = AttributesEnum.BandelId.index();
    public static final int PLYFROM = AttributesEnum.Plyfrom.index();
    public static final int PLYTO = AttributesEnum.Plyto.index();
    public static final int CUTTINGQTY = AttributesEnum.Cuttingqty.index();
    public static final int FABCONS = AttributesEnum.FabCons.index();
    public static final int LASTUPDATEDATE = AttributesEnum.LastUpdateDate.index();
    public static final int LASTUPDATEDBY = AttributesEnum.LastUpdatedBy.index();
    public static final int CREATIONDATE = AttributesEnum.CreationDate.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int DETAILEO = AttributesEnum.DetailEO.index();

    /**
     * This is the default constructor (do not remove).
     */
    public BundleEOImpl() {
    }


    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        if (mDefinitionObject == null) {
            mDefinitionObject = EntityDefImpl.findDefObject("mnj.ont.model.entities.BundleEO");
        }
        return mDefinitionObject;
    }

    /**
     * Gets the attribute value for DivisionId, using the alias name DivisionId.
     * @return the DivisionId
     */
    public String getDivisionId() {
        return (String)getAttributeInternal(DIVISIONID);
    }

    /**
     * Sets <code>value</code> as the attribute value for DivisionId.
     * @param value value to set the DivisionId
     */
    public void setDivisionId(String value) {
        setAttributeInternal(DIVISIONID, value);
    }

    /**
     * Gets the attribute value for RangeId, using the alias name RangeId.
     * @return the RangeId
     */
    public Number getRangeId() {
        return (Number)getAttributeInternal(RANGEID);
    }

    /**
     * Sets <code>value</code> as the attribute value for RangeId.
     * @param value value to set the RangeId
     */
    public void setRangeId(Number value) {
        setAttributeInternal(RANGEID, value);
    }

    /**
     * Gets the attribute value for RangebndlineId, using the alias name RangebndlineId.
     * @return the RangebndlineId
     */
    public Number getRangebndlineId() {
        return (Number)getAttributeInternal(RANGEBNDLINEID);
    }

    /**
     * Sets <code>value</code> as the attribute value for RangebndlineId.
     * @param value value to set the RangebndlineId
     */
    public void setRangebndlineId(Number value) {
        setAttributeInternal(RANGEBNDLINEID, value);
    }

    /**
     * Gets the attribute value for RangeoblineId, using the alias name RangeoblineId.
     * @return the RangeoblineId
     */
    public Number getRangeoblineId() {
        return (Number)getAttributeInternal(RANGEOBLINEID);
    }

    /**
     * Sets <code>value</code> as the attribute value for RangeoblineId.
     * @param value value to set the RangeoblineId
     */
    public void setRangeoblineId(Number value) {
        setAttributeInternal(RANGEOBLINEID, value);
    }

    /**
     * Gets the attribute value for SalesorderId, using the alias name SalesorderId.
     * @return the SalesorderId
     */
    public String getSalesorderId() {
        return (String)getAttributeInternal(SALESORDERID);
    }

    /**
     * Sets <code>value</code> as the attribute value for SalesorderId.
     * @param value value to set the SalesorderId
     */
    public void setSalesorderId(String value) {
        setAttributeInternal(SALESORDERID, value);
    }

    /**
     * Gets the attribute value for Shade, using the alias name Shade.
     * @return the Shade
     */
    public String getShade() {
        return (String)getAttributeInternal(SHADE);
    }

    /**
     * Sets <code>value</code> as the attribute value for Shade.
     * @param value value to set the Shade
     */
    public void setShade(String value) {
        setAttributeInternal(SHADE, value);
    }

    /**
     * Gets the attribute value for BandelId, using the alias name BandelId.
     * @return the BandelId
     */
    public String getBandelId() {
        return (String)getAttributeInternal(BANDELID);
    }

    /**
     * Sets <code>value</code> as the attribute value for BandelId.
     * @param value value to set the BandelId
     */
    public void setBandelId(String value) {
        setAttributeInternal(BANDELID, value);
    }

    /**
     * Gets the attribute value for Plyfrom, using the alias name Plyfrom.
     * @return the Plyfrom
     */
    public Number getPlyfrom() {
        return (Number)getAttributeInternal(PLYFROM);
    }

    /**
     * Sets <code>value</code> as the attribute value for Plyfrom.
     * @param value value to set the Plyfrom
     */
    public void setPlyfrom(Number value) {
        setAttributeInternal(PLYFROM, value);
    }

    /**
     * Gets the attribute value for Plyto, using the alias name Plyto.
     * @return the Plyto
     */
    public Number getPlyto() {
        return (Number)getAttributeInternal(PLYTO);
    }

    /**
     * Sets <code>value</code> as the attribute value for Plyto.
     * @param value value to set the Plyto
     */
    public void setPlyto(Number value) {
        setAttributeInternal(PLYTO, value);
    }

    /**
     * Gets the attribute value for Cuttingqty, using the alias name Cuttingqty.
     * @return the Cuttingqty
     */
    public Number getCuttingqty() {
        return (Number)getAttributeInternal(CUTTINGQTY);
    }

    /**
     * Sets <code>value</code> as the attribute value for Cuttingqty.
     * @param value value to set the Cuttingqty
     */
    public void setCuttingqty(Number value) {
        setAttributeInternal(CUTTINGQTY, value);
    }

    /**
     * Gets the attribute value for FabCons, using the alias name FabCons.
     * @return the FabCons
     */
    public Number getFabCons() {
        return (Number)getAttributeInternal(FABCONS);
    }

    /**
     * Sets <code>value</code> as the attribute value for FabCons.
     * @param value value to set the FabCons
     */
    public void setFabCons(Number value) {
        setAttributeInternal(FABCONS, value);
    }

    /**
     * Gets the attribute value for LastUpdateDate, using the alias name LastUpdateDate.
     * @return the LastUpdateDate
     */
    public Date getLastUpdateDate() {
        return (Date)getAttributeInternal(LASTUPDATEDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for LastUpdateDate.
     * @param value value to set the LastUpdateDate
     */
    public void setLastUpdateDate(Date value) {
        setAttributeInternal(LASTUPDATEDATE, value);
    }

    /**
     * Gets the attribute value for LastUpdatedBy, using the alias name LastUpdatedBy.
     * @return the LastUpdatedBy
     */
    public Number getLastUpdatedBy() {
        return (Number)getAttributeInternal(LASTUPDATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for LastUpdatedBy.
     * @param value value to set the LastUpdatedBy
     */
    public void setLastUpdatedBy(Number value) {
        setAttributeInternal(LASTUPDATEDBY, value);
    }

    /**
     * Gets the attribute value for CreationDate, using the alias name CreationDate.
     * @return the CreationDate
     */
    public Date getCreationDate() {
        return (Date)getAttributeInternal(CREATIONDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreationDate.
     * @param value value to set the CreationDate
     */
    public void setCreationDate(Date value) {
        setAttributeInternal(CREATIONDATE, value);
    }

    /**
     * Gets the attribute value for CreatedBy, using the alias name CreatedBy.
     * @return the CreatedBy
     */
    public Number getCreatedBy() {
        return (Number)getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreatedBy.
     * @param value value to set the CreatedBy
     */
    public void setCreatedBy(Number value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }

    /**
     * @return the associated entity DetailEOImpl.
     */
    public DetailEOImpl getDetailEO() {
        return (DetailEOImpl)getAttributeInternal(DETAILEO);
    }

    /**
     * Sets <code>value</code> as the associated entity DetailEOImpl.
     */
    public void setDetailEO(DetailEOImpl value) {
        setAttributeInternal(DETAILEO, value);
    }
    protected void create(AttributeList attributeList) {
        super.create(attributeList);
    
           oracle.jbo.server.SequenceImpl s =new oracle.jbo.server.SequenceImpl("MNJ_MFG_RANGE_BANDELLINE_S",getDBTransaction());
           oracle.jbo.domain.Number sVal = s.getSequenceNumber();
           setRangebndlineId(sVal);
    
    }
    /**
     * @param rangeId key constituent
     * @param rangebndlineId key constituent
     * @param rangeoblineId key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(Number rangeId, Number rangebndlineId,
                                       Number rangeoblineId) {
        return new Key(new Object[]{rangeId, rangebndlineId, rangeoblineId});
    }


}
