package mnj.ont.model.entities;

import oracle.jbo.AttributeList;
import oracle.jbo.Key;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.TransactionEvent;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Mar 24 15:57:16 PKT 2015
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class DetailEOtodetailEoImpl extends EntityImpl {
    private static EntityDefImpl mDefinitionObject;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. Do not modify.
     */
    public enum AttributesEnum {
        DivisionId {
            public Object get(DetailEOtodetailEoImpl obj) {
                return obj.getDivisionId();
            }

            public void put(DetailEOtodetailEoImpl obj, Object value) {
                obj.setDivisionId((String)value);
            }
        }
        ,
        RangeId {
            public Object get(DetailEOtodetailEoImpl obj) {
                return obj.getRangeId();
            }

            public void put(DetailEOtodetailEoImpl obj, Object value) {
                obj.setRangeId((Number)value);
            }
        }
        ,
        RangeoblineId {
            public Object get(DetailEOtodetailEoImpl obj) {
                return obj.getRangeoblineId();
            }

            public void put(DetailEOtodetailEoImpl obj, Object value) {
                obj.setRangeoblineId((Number)value);
            }
        }
        ,
        RangobszlineId {
            public Object get(DetailEOtodetailEoImpl obj) {
                return obj.getRangobszlineId();
            }

            public void put(DetailEOtodetailEoImpl obj, Object value) {
                obj.setRangobszlineId((Number)value);
            }
        }
        ,
        SalesorderId {
            public Object get(DetailEOtodetailEoImpl obj) {
                return obj.getSalesorderId();
            }

            public void put(DetailEOtodetailEoImpl obj, Object value) {
                obj.setSalesorderId((Number)value);
            }
        }
        ,
        SolineId {
            public Object get(DetailEOtodetailEoImpl obj) {
                return obj.getSolineId();
            }

            public void put(DetailEOtodetailEoImpl obj, Object value) {
                obj.setSolineId((Number)value);
            }
        }
        ,
        InseamId {
            public Object get(DetailEOtodetailEoImpl obj) {
                return obj.getInseamId();
            }

            public void put(DetailEOtodetailEoImpl obj, Object value) {
                obj.setInseamId((String)value);
            }
        }
        ,
        SizegroupId {
            public Object get(DetailEOtodetailEoImpl obj) {
                return obj.getSizegroupId();
            }

            public void put(DetailEOtodetailEoImpl obj, Object value) {
                obj.setSizegroupId((String)value);
            }
        }
        ,
        SizeId {
            public Object get(DetailEOtodetailEoImpl obj) {
                return obj.getSizeId();
            }

            public void put(DetailEOtodetailEoImpl obj, Object value) {
                obj.setSizeId((String)value);
            }
        }
        ,
        CutQuantity {
            public Object get(DetailEOtodetailEoImpl obj) {
                return obj.getCutQuantity();
            }

            public void put(DetailEOtodetailEoImpl obj, Object value) {
                obj.setCutQuantity((Number)value);
            }
        }
        ,
        CutrejQuantity {
            public Object get(DetailEOtodetailEoImpl obj) {
                return obj.getCutrejQuantity();
            }

            public void put(DetailEOtodetailEoImpl obj, Object value) {
                obj.setCutrejQuantity((Number)value);
            }
        }
        ,
        LastUpdateDate {
            public Object get(DetailEOtodetailEoImpl obj) {
                return obj.getLastUpdateDate();
            }

            public void put(DetailEOtodetailEoImpl obj, Object value) {
                obj.setLastUpdateDate((Date)value);
            }
        }
        ,
        LastUpdatedBy {
            public Object get(DetailEOtodetailEoImpl obj) {
                return obj.getLastUpdatedBy();
            }

            public void put(DetailEOtodetailEoImpl obj, Object value) {
                obj.setLastUpdatedBy((Number)value);
            }
        }
        ,
        CreationDate {
            public Object get(DetailEOtodetailEoImpl obj) {
                return obj.getCreationDate();
            }

            public void put(DetailEOtodetailEoImpl obj, Object value) {
                obj.setCreationDate((Date)value);
            }
        }
        ,
        CreatedBy {
            public Object get(DetailEOtodetailEoImpl obj) {
                return obj.getCreatedBy();
            }

            public void put(DetailEOtodetailEoImpl obj, Object value) {
                obj.setCreatedBy((Number)value);
            }
        }
        ,
        LastUpdateLogin {
            public Object get(DetailEOtodetailEoImpl obj) {
                return obj.getLastUpdateLogin();
            }

            public void put(DetailEOtodetailEoImpl obj, Object value) {
                obj.setLastUpdateLogin((Number)value);
            }
        }
        ,
        Attribute1 {
            public Object get(DetailEOtodetailEoImpl obj) {
                return obj.getAttribute1();
            }

            public void put(DetailEOtodetailEoImpl obj, Object value) {
                obj.setAttribute1((String)value);
            }
        }
        ,
        Attribute2 {
            public Object get(DetailEOtodetailEoImpl obj) {
                return obj.getAttribute2();
            }

            public void put(DetailEOtodetailEoImpl obj, Object value) {
                obj.setAttribute2((String)value);
            }
        }
        ,
        Attribute3 {
            public Object get(DetailEOtodetailEoImpl obj) {
                return obj.getAttribute3();
            }

            public void put(DetailEOtodetailEoImpl obj, Object value) {
                obj.setAttribute3((String)value);
            }
        }
        ,
        Attribute4 {
            public Object get(DetailEOtodetailEoImpl obj) {
                return obj.getAttribute4();
            }

            public void put(DetailEOtodetailEoImpl obj, Object value) {
                obj.setAttribute4((String)value);
            }
        }
        ,
        Attribute5 {
            public Object get(DetailEOtodetailEoImpl obj) {
                return obj.getAttribute5();
            }

            public void put(DetailEOtodetailEoImpl obj, Object value) {
                obj.setAttribute5((String)value);
            }
        }
        ,
        Attribute6 {
            public Object get(DetailEOtodetailEoImpl obj) {
                return obj.getAttribute6();
            }

            public void put(DetailEOtodetailEoImpl obj, Object value) {
                obj.setAttribute6((String)value);
            }
        }
        ,
        Attribute7 {
            public Object get(DetailEOtodetailEoImpl obj) {
                return obj.getAttribute7();
            }

            public void put(DetailEOtodetailEoImpl obj, Object value) {
                obj.setAttribute7((String)value);
            }
        }
        ,
        Attribute8 {
            public Object get(DetailEOtodetailEoImpl obj) {
                return obj.getAttribute8();
            }

            public void put(DetailEOtodetailEoImpl obj, Object value) {
                obj.setAttribute8((String)value);
            }
        }
        ,
        Attribute9 {
            public Object get(DetailEOtodetailEoImpl obj) {
                return obj.getAttribute9();
            }

            public void put(DetailEOtodetailEoImpl obj, Object value) {
                obj.setAttribute9((String)value);
            }
        }
        ,
        Attribute10 {
            public Object get(DetailEOtodetailEoImpl obj) {
                return obj.getAttribute10();
            }

            public void put(DetailEOtodetailEoImpl obj, Object value) {
                obj.setAttribute10((String)value);
            }
        }
        ,
        Attribute11 {
            public Object get(DetailEOtodetailEoImpl obj) {
                return obj.getAttribute11();
            }

            public void put(DetailEOtodetailEoImpl obj, Object value) {
                obj.setAttribute11((String)value);
            }
        }
        ,
        Attribute12 {
            public Object get(DetailEOtodetailEoImpl obj) {
                return obj.getAttribute12();
            }

            public void put(DetailEOtodetailEoImpl obj, Object value) {
                obj.setAttribute12((String)value);
            }
        }
        ,
        Attribute13 {
            public Object get(DetailEOtodetailEoImpl obj) {
                return obj.getAttribute13();
            }

            public void put(DetailEOtodetailEoImpl obj, Object value) {
                obj.setAttribute13((String)value);
            }
        }
        ,
        Attribute14 {
            public Object get(DetailEOtodetailEoImpl obj) {
                return obj.getAttribute14();
            }

            public void put(DetailEOtodetailEoImpl obj, Object value) {
                obj.setAttribute14((String)value);
            }
        }
        ,
        Attribute15 {
            public Object get(DetailEOtodetailEoImpl obj) {
                return obj.getAttribute15();
            }

            public void put(DetailEOtodetailEoImpl obj, Object value) {
                obj.setAttribute15((String)value);
            }
        }
        ,
        OrderQty {
            public Object get(DetailEOtodetailEoImpl obj) {
                return obj.getOrderQty();
            }

            public void put(DetailEOtodetailEoImpl obj, Object value) {
                obj.setOrderQty((Number)value);
            }
        }
        ,
        PreQty {
            public Object get(DetailEOtodetailEoImpl obj) {
                return obj.getPreQty();
            }

            public void put(DetailEOtodetailEoImpl obj, Object value) {
                obj.setPreQty((Number)value);
            }
        }
        ,
        BalanceQty {
            public Object get(DetailEOtodetailEoImpl obj) {
                return obj.getBalanceQty();
            }

            public void put(DetailEOtodetailEoImpl obj, Object value) {
                obj.setBalanceQty((Number)value);
            }
        }
        ,
        DetailEO {
            public Object get(DetailEOtodetailEoImpl obj) {
                return obj.getDetailEO();
            }

            public void put(DetailEOtodetailEoImpl obj, Object value) {
                obj.setDetailEO((DetailEOImpl)value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static int firstIndex = 0;

        public abstract Object get(DetailEOtodetailEoImpl object);

        public abstract void put(DetailEOtodetailEoImpl object, Object value);

        public int index() {
            return DetailEOtodetailEoImpl.AttributesEnum.firstIndex() + ordinal();
        }

        public static int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return DetailEOtodetailEoImpl.AttributesEnum.firstIndex() + DetailEOtodetailEoImpl.AttributesEnum.staticValues().length;
        }

        public static AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = DetailEOtodetailEoImpl.AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int DIVISIONID = AttributesEnum.DivisionId.index();
    public static final int RANGEID = AttributesEnum.RangeId.index();
    public static final int RANGEOBLINEID = AttributesEnum.RangeoblineId.index();
    public static final int RANGOBSZLINEID = AttributesEnum.RangobszlineId.index();
    public static final int SALESORDERID = AttributesEnum.SalesorderId.index();
    public static final int SOLINEID = AttributesEnum.SolineId.index();
    public static final int INSEAMID = AttributesEnum.InseamId.index();
    public static final int SIZEGROUPID = AttributesEnum.SizegroupId.index();
    public static final int SIZEID = AttributesEnum.SizeId.index();
    public static final int CUTQUANTITY = AttributesEnum.CutQuantity.index();
    public static final int CUTREJQUANTITY = AttributesEnum.CutrejQuantity.index();
    public static final int LASTUPDATEDATE = AttributesEnum.LastUpdateDate.index();
    public static final int LASTUPDATEDBY = AttributesEnum.LastUpdatedBy.index();
    public static final int CREATIONDATE = AttributesEnum.CreationDate.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int LASTUPDATELOGIN = AttributesEnum.LastUpdateLogin.index();
    public static final int ATTRIBUTE1 = AttributesEnum.Attribute1.index();
    public static final int ATTRIBUTE2 = AttributesEnum.Attribute2.index();
    public static final int ATTRIBUTE3 = AttributesEnum.Attribute3.index();
    public static final int ATTRIBUTE4 = AttributesEnum.Attribute4.index();
    public static final int ATTRIBUTE5 = AttributesEnum.Attribute5.index();
    public static final int ATTRIBUTE6 = AttributesEnum.Attribute6.index();
    public static final int ATTRIBUTE7 = AttributesEnum.Attribute7.index();
    public static final int ATTRIBUTE8 = AttributesEnum.Attribute8.index();
    public static final int ATTRIBUTE9 = AttributesEnum.Attribute9.index();
    public static final int ATTRIBUTE10 = AttributesEnum.Attribute10.index();
    public static final int ATTRIBUTE11 = AttributesEnum.Attribute11.index();
    public static final int ATTRIBUTE12 = AttributesEnum.Attribute12.index();
    public static final int ATTRIBUTE13 = AttributesEnum.Attribute13.index();
    public static final int ATTRIBUTE14 = AttributesEnum.Attribute14.index();
    public static final int ATTRIBUTE15 = AttributesEnum.Attribute15.index();
    public static final int ORDERQTY = AttributesEnum.OrderQty.index();
    public static final int PREQTY = AttributesEnum.PreQty.index();
    public static final int BALANCEQTY = AttributesEnum.BalanceQty.index();
    public static final int DETAILEO = AttributesEnum.DetailEO.index();

    /**
     * This is the default constructor (do not remove).
     */
    public DetailEOtodetailEoImpl() {
    }


    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        if (mDefinitionObject == null) {
            mDefinitionObject = EntityDefImpl.findDefObject("mnj.ont.model.entities.DetailEOtodetailEo");
        }
        return mDefinitionObject;
    }

    /**
     * Gets the attribute value for DivisionId, using the alias name DivisionId.
     * @return the DivisionId
     */
    public String getDivisionId() {
        return (String)getAttributeInternal(DIVISIONID);
    }

    /**
     * Sets <code>value</code> as the attribute value for DivisionId.
     * @param value value to set the DivisionId
     */
    public void setDivisionId(String value) {
        setAttributeInternal(DIVISIONID, value);
    }

    /**
     * Gets the attribute value for RangeId, using the alias name RangeId.
     * @return the RangeId
     */
    public Number getRangeId() {
        return (Number)getAttributeInternal(RANGEID);
    }

    /**
     * Sets <code>value</code> as the attribute value for RangeId.
     * @param value value to set the RangeId
     */
    public void setRangeId(Number value) {
        setAttributeInternal(RANGEID, value);
    }

    /**
     * Gets the attribute value for RangeoblineId, using the alias name RangeoblineId.
     * @return the RangeoblineId
     */
    public Number getRangeoblineId() {
        return (Number)getAttributeInternal(RANGEOBLINEID);
    }

    /**
     * Sets <code>value</code> as the attribute value for RangeoblineId.
     * @param value value to set the RangeoblineId
     */
    public void setRangeoblineId(Number value) {
        setAttributeInternal(RANGEOBLINEID, value);
    }

    /**
     * Gets the attribute value for RangobszlineId, using the alias name RangobszlineId.
     * @return the RangobszlineId
     */
    public Number getRangobszlineId() {
        return (Number)getAttributeInternal(RANGOBSZLINEID);
    }

    /**
     * Sets <code>value</code> as the attribute value for RangobszlineId.
     * @param value value to set the RangobszlineId
     */
    public void setRangobszlineId(Number value) {
        setAttributeInternal(RANGOBSZLINEID, value);
    }

    /**
     * Gets the attribute value for SalesorderId, using the alias name SalesorderId.
     * @return the SalesorderId
     */
    public Number getSalesorderId() {
        return (Number)getAttributeInternal(SALESORDERID);
    }

    /**
     * Sets <code>value</code> as the attribute value for SalesorderId.
     * @param value value to set the SalesorderId
     */
    public void setSalesorderId(Number value) {
        setAttributeInternal(SALESORDERID, value);
    }

    /**
     * Gets the attribute value for SolineId, using the alias name SolineId.
     * @return the SolineId
     */
    public Number getSolineId() {
        return (Number)getAttributeInternal(SOLINEID);
    }

    /**
     * Sets <code>value</code> as the attribute value for SolineId.
     * @param value value to set the SolineId
     */
    public void setSolineId(Number value) {
        setAttributeInternal(SOLINEID, value);
    }

    /**
     * Gets the attribute value for InseamId, using the alias name InseamId.
     * @return the InseamId
     */
    public String getInseamId() {
        return (String)getAttributeInternal(INSEAMID);
    }

    /**
     * Sets <code>value</code> as the attribute value for InseamId.
     * @param value value to set the InseamId
     */
    public void setInseamId(String value) {
        setAttributeInternal(INSEAMID, value);
    }

    /**
     * Gets the attribute value for SizegroupId, using the alias name SizegroupId.
     * @return the SizegroupId
     */
    public String getSizegroupId() {
        return (String)getAttributeInternal(SIZEGROUPID);
    }

    /**
     * Sets <code>value</code> as the attribute value for SizegroupId.
     * @param value value to set the SizegroupId
     */
    public void setSizegroupId(String value) {
        setAttributeInternal(SIZEGROUPID, value);
    }

    /**
     * Gets the attribute value for SizeId, using the alias name SizeId.
     * @return the SizeId
     */
    public String getSizeId() {
        return (String)getAttributeInternal(SIZEID);
    }

    /**
     * Sets <code>value</code> as the attribute value for SizeId.
     * @param value value to set the SizeId
     */
    public void setSizeId(String value) {
        setAttributeInternal(SIZEID, value);
    }

    /**
     * Gets the attribute value for CutQuantity, using the alias name CutQuantity.
     * @return the CutQuantity
     */
    public Number getCutQuantity() {
        return (Number)getAttributeInternal(CUTQUANTITY);
    }

    /**
     * Sets <code>value</code> as the attribute value for CutQuantity.
     * @param value value to set the CutQuantity
     */
    public void setCutQuantity(Number value) {
        setAttributeInternal(CUTQUANTITY, value);
    }

    /**
     * Gets the attribute value for CutrejQuantity, using the alias name CutrejQuantity.
     * @return the CutrejQuantity
     */
    public Number getCutrejQuantity() {
        return (Number)getAttributeInternal(CUTREJQUANTITY);
    }

    /**
     * Sets <code>value</code> as the attribute value for CutrejQuantity.
     * @param value value to set the CutrejQuantity
     */
    public void setCutrejQuantity(Number value) {
        setAttributeInternal(CUTREJQUANTITY, value);
    }

    /**
     * Gets the attribute value for LastUpdateDate, using the alias name LastUpdateDate.
     * @return the LastUpdateDate
     */
    public Date getLastUpdateDate() {
        return (Date)getAttributeInternal(LASTUPDATEDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for LastUpdateDate.
     * @param value value to set the LastUpdateDate
     */
    public void setLastUpdateDate(Date value) {
        setAttributeInternal(LASTUPDATEDATE, value);
    }

    /**
     * Gets the attribute value for LastUpdatedBy, using the alias name LastUpdatedBy.
     * @return the LastUpdatedBy
     */
    public Number getLastUpdatedBy() {
        return (Number)getAttributeInternal(LASTUPDATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for LastUpdatedBy.
     * @param value value to set the LastUpdatedBy
     */
    public void setLastUpdatedBy(Number value) {
        setAttributeInternal(LASTUPDATEDBY, value);
    }

    /**
     * Gets the attribute value for CreationDate, using the alias name CreationDate.
     * @return the CreationDate
     */
    public Date getCreationDate() {
        return (Date)getAttributeInternal(CREATIONDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreationDate.
     * @param value value to set the CreationDate
     */
    public void setCreationDate(Date value) {
        setAttributeInternal(CREATIONDATE, value);
    }

    /**
     * Gets the attribute value for CreatedBy, using the alias name CreatedBy.
     * @return the CreatedBy
     */
    public Number getCreatedBy() {
        return (Number)getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreatedBy.
     * @param value value to set the CreatedBy
     */
    public void setCreatedBy(Number value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for LastUpdateLogin, using the alias name LastUpdateLogin.
     * @return the LastUpdateLogin
     */
    public Number getLastUpdateLogin() {
        return (Number)getAttributeInternal(LASTUPDATELOGIN);
    }

    /**
     * Sets <code>value</code> as the attribute value for LastUpdateLogin.
     * @param value value to set the LastUpdateLogin
     */
    public void setLastUpdateLogin(Number value) {
        setAttributeInternal(LASTUPDATELOGIN, value);
    }

    /**
     * Gets the attribute value for Attribute1, using the alias name Attribute1.
     * @return the Attribute1
     */
    public String getAttribute1() {
        return (String)getAttributeInternal(ATTRIBUTE1);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute1.
     * @param value value to set the Attribute1
     */
    public void setAttribute1(String value) {
        setAttributeInternal(ATTRIBUTE1, value);
    }

    /**
     * Gets the attribute value for Attribute2, using the alias name Attribute2.
     * @return the Attribute2
     */
    public String getAttribute2() {
        return (String)getAttributeInternal(ATTRIBUTE2);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute2.
     * @param value value to set the Attribute2
     */
    public void setAttribute2(String value) {
        setAttributeInternal(ATTRIBUTE2, value);
    }

    /**
     * Gets the attribute value for Attribute3, using the alias name Attribute3.
     * @return the Attribute3
     */
    public String getAttribute3() {
        return (String)getAttributeInternal(ATTRIBUTE3);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute3.
     * @param value value to set the Attribute3
     */
    public void setAttribute3(String value) {
        setAttributeInternal(ATTRIBUTE3, value);
    }

    /**
     * Gets the attribute value for Attribute4, using the alias name Attribute4.
     * @return the Attribute4
     */
    public String getAttribute4() {
        return (String)getAttributeInternal(ATTRIBUTE4);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute4.
     * @param value value to set the Attribute4
     */
    public void setAttribute4(String value) {
        setAttributeInternal(ATTRIBUTE4, value);
    }

    /**
     * Gets the attribute value for Attribute5, using the alias name Attribute5.
     * @return the Attribute5
     */
    public String getAttribute5() {
        return (String)getAttributeInternal(ATTRIBUTE5);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute5.
     * @param value value to set the Attribute5
     */
    public void setAttribute5(String value) {
        setAttributeInternal(ATTRIBUTE5, value);
    }

    /**
     * Gets the attribute value for Attribute6, using the alias name Attribute6.
     * @return the Attribute6
     */
    public String getAttribute6() {
        return (String)getAttributeInternal(ATTRIBUTE6);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute6.
     * @param value value to set the Attribute6
     */
    public void setAttribute6(String value) {
        setAttributeInternal(ATTRIBUTE6, value);
    }

    /**
     * Gets the attribute value for Attribute7, using the alias name Attribute7.
     * @return the Attribute7
     */
    public String getAttribute7() {
        return (String)getAttributeInternal(ATTRIBUTE7);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute7.
     * @param value value to set the Attribute7
     */
    public void setAttribute7(String value) {
        setAttributeInternal(ATTRIBUTE7, value);
    }

    /**
     * Gets the attribute value for Attribute8, using the alias name Attribute8.
     * @return the Attribute8
     */
    public String getAttribute8() {
        return (String)getAttributeInternal(ATTRIBUTE8);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute8.
     * @param value value to set the Attribute8
     */
    public void setAttribute8(String value) {
        setAttributeInternal(ATTRIBUTE8, value);
    }

    /**
     * Gets the attribute value for Attribute9, using the alias name Attribute9.
     * @return the Attribute9
     */
    public String getAttribute9() {
        return (String)getAttributeInternal(ATTRIBUTE9);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute9.
     * @param value value to set the Attribute9
     */
    public void setAttribute9(String value) {
        setAttributeInternal(ATTRIBUTE9, value);
    }

    /**
     * Gets the attribute value for Attribute10, using the alias name Attribute10.
     * @return the Attribute10
     */
    public String getAttribute10() {
        return (String)getAttributeInternal(ATTRIBUTE10);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute10.
     * @param value value to set the Attribute10
     */
    public void setAttribute10(String value) {
        setAttributeInternal(ATTRIBUTE10, value);
    }

    /**
     * Gets the attribute value for Attribute11, using the alias name Attribute11.
     * @return the Attribute11
     */
    public String getAttribute11() {
        return (String)getAttributeInternal(ATTRIBUTE11);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute11.
     * @param value value to set the Attribute11
     */
    public void setAttribute11(String value) {
        setAttributeInternal(ATTRIBUTE11, value);
    }

    /**
     * Gets the attribute value for Attribute12, using the alias name Attribute12.
     * @return the Attribute12
     */
    public String getAttribute12() {
        return (String)getAttributeInternal(ATTRIBUTE12);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute12.
     * @param value value to set the Attribute12
     */
    public void setAttribute12(String value) {
        setAttributeInternal(ATTRIBUTE12, value);
    }

    /**
     * Gets the attribute value for Attribute13, using the alias name Attribute13.
     * @return the Attribute13
     */
    public String getAttribute13() {
        return (String)getAttributeInternal(ATTRIBUTE13);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute13.
     * @param value value to set the Attribute13
     */
    public void setAttribute13(String value) {
        setAttributeInternal(ATTRIBUTE13, value);
    }

    /**
     * Gets the attribute value for Attribute14, using the alias name Attribute14.
     * @return the Attribute14
     */
    public String getAttribute14() {
        return (String)getAttributeInternal(ATTRIBUTE14);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute14.
     * @param value value to set the Attribute14
     */
    public void setAttribute14(String value) {
        setAttributeInternal(ATTRIBUTE14, value);
    }

    /**
     * Gets the attribute value for Attribute15, using the alias name Attribute15.
     * @return the Attribute15
     */
    public String getAttribute15() {
        return (String)getAttributeInternal(ATTRIBUTE15);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute15.
     * @param value value to set the Attribute15
     */
    public void setAttribute15(String value) {
        setAttributeInternal(ATTRIBUTE15, value);
    }

    /**
     * Gets the attribute value for OrderQty, using the alias name OrderQty.
     * @return the OrderQty
     */
    public Number getOrderQty() {
        return (Number)getAttributeInternal(ORDERQTY);
    }

    /**
     * Sets <code>value</code> as the attribute value for OrderQty.
     * @param value value to set the OrderQty
     */
    public void setOrderQty(Number value) {
        setAttributeInternal(ORDERQTY, value);
    }

    /**
     * Gets the attribute value for PreQty, using the alias name PreQty.
     * @return the PreQty
     */
    public Number getPreQty() {
        return (Number)getAttributeInternal(PREQTY);
    }

    /**
     * Sets <code>value</code> as the attribute value for PreQty.
     * @param value value to set the PreQty
     */
    public void setPreQty(Number value) {
        setAttributeInternal(PREQTY, value);
    }

    /**
     * Gets the attribute value for BalanceQty, using the alias name BalanceQty.
     * @return the BalanceQty
     */
    public Number getBalanceQty() {
        return (Number)getAttributeInternal(BALANCEQTY);
    }

    /**
     * Sets <code>value</code> as the attribute value for BalanceQty.
     * @param value value to set the BalanceQty
     */
    public void setBalanceQty(Number value) {
        setAttributeInternal(BALANCEQTY, value);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }

    /**
     * @return the associated entity DetailEOImpl.
     */
    public DetailEOImpl getDetailEO() {
        return (DetailEOImpl)getAttributeInternal(DETAILEO);
    }

    /**
     * Sets <code>value</code> as the associated entity DetailEOImpl.
     */
    public void setDetailEO(DetailEOImpl value) {
        setAttributeInternal(DETAILEO, value);
    }


    /**
     * @param rangeId key constituent
     * @param rangeoblineId key constituent
     * @param rangobszlineId key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(Number rangeId, Number rangeoblineId,
                                       Number rangobszlineId) {
        return new Key(new Object[]{rangeId, rangeoblineId, rangobszlineId});
    }

    /**
     * Add attribute defaulting logic in this method.
     * @param attributeList list of attribute names/values to initialize the row
     */
    protected void create(AttributeList attributeList) {
        super.create(attributeList);
        Integer empno =Integer.parseInt(new oracle.jbo.server.SequenceImpl("MNJ_MFG_RANGE_SIZLINE_S", getDBTransaction()).getSequenceNumber().toString());
               oracle.jbo.server.SequenceImpl s =new oracle.jbo.server.SequenceImpl("MNJ_MFG_RANGE_SIZLINE_S",getDBTransaction());
               oracle.jbo.domain.Number sVal = s.getSequenceNumber();
               setRangobszlineId(sVal);
    }

    /**
     * Add entity remove logic in this method.
     */
    public void remove() {
        super.remove();
    }

    /**
     * Add locking logic here.
     */
    public void lock() {
        super.lock();
    }
    

    /**
     * Custom DML update/insert/delete logic here.
     * @param operation the operation type
     * @param e the transaction event
     */
    protected void doDML(int operation, TransactionEvent e) {
        super.doDML(operation, e);
    }
}
