package mnj.ont.model.entities;

import java.sql.SQLException;

import java.util.Map;

import oracle.adf.share.ADFContext;

import oracle.jbo.AttributeList;
import oracle.jbo.Key;
import oracle.jbo.RowIterator;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.TransactionEvent;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Mar 24 18:03:51 PKT 2015
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class DetailEOImpl extends EntityImpl {
    private static EntityDefImpl mDefinitionObject;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. Do not modify.
     */
    public enum AttributesEnum {
        DivisionId {
            public Object get(DetailEOImpl obj) {
                return obj.getDivisionId();
            }

            public void put(DetailEOImpl obj, Object value) {
                obj.setDivisionId((String)value);
            }
        }
        ,
        RangeId {
            public Object get(DetailEOImpl obj) {
                return obj.getRangeId();
            }

            public void put(DetailEOImpl obj, Object value) {
                obj.setRangeId((Number)value);
            }
        }
        ,
        RangeoblineId {
            public Object get(DetailEOImpl obj) {
                return obj.getRangeoblineId();
            }

            public void put(DetailEOImpl obj, Object value) {
                obj.setRangeoblineId((Number)value);
            }
        }
        ,
        SalesorderId {
            public Object get(DetailEOImpl obj) {
                return obj.getSalesorderId();
            }

            public void put(DetailEOImpl obj, Object value) {
                obj.setSalesorderId((String)value);
            }
        }
        ,
        SolineId {
            public Object get(DetailEOImpl obj) {
                return obj.getSolineId();
            }

            public void put(DetailEOImpl obj, Object value) {
                obj.setSolineId((Number)value);
            }
        }
        ,
        ItemCode {
            public Object get(DetailEOImpl obj) {
                return obj.getItemCode();
            }

            public void put(DetailEOImpl obj, Object value) {
                obj.setItemCode((String)value);
            }
        }
        ,
        CutjobId {
            public Object get(DetailEOImpl obj) {
                return obj.getCutjobId();
            }

            public void put(DetailEOImpl obj, Object value) {
                obj.setCutjobId((String)value);
            }
        }
        ,
        InseamId {
            public Object get(DetailEOImpl obj) {
                return obj.getInseamId();
            }

            public void put(DetailEOImpl obj, Object value) {
                obj.setInseamId((String)value);
            }
        }
        ,
        Cuttingqty {
            public Object get(DetailEOImpl obj) {
                return obj.getCuttingqty();
            }

            public void put(DetailEOImpl obj, Object value) {
                obj.setCuttingqty((Number)value);
            }
        }
        ,
        Rajqty {
            public Object get(DetailEOImpl obj) {
                return obj.getRajqty();
            }

            public void put(DetailEOImpl obj, Object value) {
                obj.setRajqty((Number)value);
            }
        }
        ,
        FabCons {
            public Object get(DetailEOImpl obj) {
                return obj.getFabCons();
            }

            public void put(DetailEOImpl obj, Object value) {
                obj.setFabCons((Number)value);
            }
        }
        ,
        LastUpdateDate {
            public Object get(DetailEOImpl obj) {
                return obj.getLastUpdateDate();
            }

            public void put(DetailEOImpl obj, Object value) {
                obj.setLastUpdateDate((Date)value);
            }
        }
        ,
        LastUpdatedBy {
            public Object get(DetailEOImpl obj) {
                return obj.getLastUpdatedBy();
            }

            public void put(DetailEOImpl obj, Object value) {
                obj.setLastUpdatedBy((Number)value);
            }
        }
        ,
        CreationDate {
            public Object get(DetailEOImpl obj) {
                return obj.getCreationDate();
            }

            public void put(DetailEOImpl obj, Object value) {
                obj.setCreationDate((Date)value);
            }
        }
        ,
        CreatedBy {
            public Object get(DetailEOImpl obj) {
                return obj.getCreatedBy();
            }

            public void put(DetailEOImpl obj, Object value) {
                obj.setCreatedBy((Number)value);
            }
        }
        ,
        ObPosted {
            public Object get(DetailEOImpl obj) {
                return obj.getObPosted();
            }

            public void put(DetailEOImpl obj, Object value) {
                obj.setObPosted((String)value);
            }
        }
        ,
        Obrefno {
            public Object get(DetailEOImpl obj) {
                return obj.getObrefno();
            }

            public void put(DetailEOImpl obj, Object value) {
                obj.setObrefno((String)value);
            }
        }
        ,
        BlancQty {
            public Object get(DetailEOImpl obj) {
                return obj.getBlancQty();
            }

            public void put(DetailEOImpl obj, Object value) {
                obj.setBlancQty((Number)value);
            }
        }
        ,
        ItemDescription {
            public Object get(DetailEOImpl obj) {
                return obj.getItemDescription();
            }

            public void put(DetailEOImpl obj, Object value) {
                obj.setItemDescription((String)value);
            }
        }
        ,
        Orderqty {
            public Object get(DetailEOImpl obj) {
                return obj.getOrderqty();
            }

            public void put(DetailEOImpl obj, Object value) {
                obj.setOrderqty((Number)value);
            }
        }
        ,
        QtyWithExtra {
            public Object get(DetailEOImpl obj) {
                return obj.getQtyWithExtra();
            }

            public void put(DetailEOImpl obj, Object value) {
                obj.setQtyWithExtra((String)value);
            }
        }
        ,
        PreviousProduction {
            public Object get(DetailEOImpl obj) {
                return obj.getPreviousProduction();
            }

            public void put(DetailEOImpl obj, Object value) {
                obj.setPreviousProduction((Number)value);
            }
        }
        ,
        BalanceProduction {
            public Object get(DetailEOImpl obj) {
                return obj.getBalanceProduction();
            }

            public void put(DetailEOImpl obj, Object value) {
                obj.setBalanceProduction((Number)value);
            }
        }
        ,
        Production {
            public Object get(DetailEOImpl obj) {
                return obj.getProduction();
            }

            public void put(DetailEOImpl obj, Object value) {
                obj.setProduction((Number)value);
            }
        }
        ,
        Attribute1 {
            public Object get(DetailEOImpl obj) {
                return obj.getAttribute1();
            }

            public void put(DetailEOImpl obj, Object value) {
                obj.setAttribute1((String)value);
            }
        }
        ,
        Attribute2 {
            public Object get(DetailEOImpl obj) {
                return obj.getAttribute2();
            }

            public void put(DetailEOImpl obj, Object value) {
                obj.setAttribute2((String)value);
            }
        }
        ,
        ErrorMessage {
            public Object get(DetailEOImpl obj) {
                return obj.getErrorMessage();
            }

            public void put(DetailEOImpl obj, Object value) {
                obj.setErrorMessage((String)value);
            }
        }
        ,
        LastAction {
            public Object get(DetailEOImpl obj) {
                return obj.getLastAction();
            }

            public void put(DetailEOImpl obj, Object value) {
                obj.setLastAction((String)value);
            }
        }
        ,
        BpoId {
            public Object get(DetailEOImpl obj) {
                return obj.getBpoId();
            }

            public void put(DetailEOImpl obj, Object value) {
                obj.setBpoId((Number)value);
            }
        }
        ,
        DetailEOtodetailEo {
            public Object get(DetailEOImpl obj) {
                return obj.getDetailEOtodetailEo();
            }

            public void put(DetailEOImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        BundleEO {
            public Object get(DetailEOImpl obj) {
                return obj.getBundleEO();
            }

            public void put(DetailEOImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        HederEO {
            public Object get(DetailEOImpl obj) {
                return obj.getHederEO();
            }

            public void put(DetailEOImpl obj, Object value) {
                obj.setHederEO((HederEOImpl)value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static int firstIndex = 0;

        public abstract Object get(DetailEOImpl object);

        public abstract void put(DetailEOImpl object, Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int DIVISIONID = AttributesEnum.DivisionId.index();
    public static final int RANGEID = AttributesEnum.RangeId.index();
    public static final int RANGEOBLINEID = AttributesEnum.RangeoblineId.index();
    public static final int SALESORDERID = AttributesEnum.SalesorderId.index();
    public static final int SOLINEID = AttributesEnum.SolineId.index();
    public static final int ITEMCODE = AttributesEnum.ItemCode.index();
    public static final int CUTJOBID = AttributesEnum.CutjobId.index();
    public static final int INSEAMID = AttributesEnum.InseamId.index();
    public static final int CUTTINGQTY = AttributesEnum.Cuttingqty.index();
    public static final int RAJQTY = AttributesEnum.Rajqty.index();
    public static final int FABCONS = AttributesEnum.FabCons.index();
    public static final int LASTUPDATEDATE = AttributesEnum.LastUpdateDate.index();
    public static final int LASTUPDATEDBY = AttributesEnum.LastUpdatedBy.index();
    public static final int CREATIONDATE = AttributesEnum.CreationDate.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int OBPOSTED = AttributesEnum.ObPosted.index();
    public static final int OBREFNO = AttributesEnum.Obrefno.index();
    public static final int BLANCQTY = AttributesEnum.BlancQty.index();
    public static final int ITEMDESCRIPTION = AttributesEnum.ItemDescription.index();
    public static final int ORDERQTY = AttributesEnum.Orderqty.index();
    public static final int QTYWITHEXTRA = AttributesEnum.QtyWithExtra.index();
    public static final int PREVIOUSPRODUCTION = AttributesEnum.PreviousProduction.index();
    public static final int BALANCEPRODUCTION = AttributesEnum.BalanceProduction.index();
    public static final int PRODUCTION = AttributesEnum.Production.index();
    public static final int ATTRIBUTE1 = AttributesEnum.Attribute1.index();
    public static final int ATTRIBUTE2 = AttributesEnum.Attribute2.index();
    public static final int ERRORMESSAGE = AttributesEnum.ErrorMessage.index();
    public static final int LASTACTION = AttributesEnum.LastAction.index();
    public static final int BPOID = AttributesEnum.BpoId.index();
    public static final int DETAILEOTODETAILEO = AttributesEnum.DetailEOtodetailEo.index();
    public static final int BUNDLEEO = AttributesEnum.BundleEO.index();
    public static final int HEDEREO = AttributesEnum.HederEO.index();

    /**
     * This is the default constructor (do not remove).
     */
    public DetailEOImpl() {
    }


    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        if (mDefinitionObject == null) {
            mDefinitionObject = EntityDefImpl.findDefObject("mnj.ont.model.entities.DetailEO");
        }
        return mDefinitionObject;
    }

    /**
     * Gets the attribute value for DivisionId, using the alias name DivisionId.
     * @return the DivisionId
     */
    public String getDivisionId() {
        return (String)getAttributeInternal(DIVISIONID);
    }

    /**
     * Sets <code>value</code> as the attribute value for DivisionId.
     * @param value value to set the DivisionId
     */
    public void setDivisionId(String value) {
        setAttributeInternal(DIVISIONID, value);
    }

    /**
     * Gets the attribute value for RangeId, using the alias name RangeId.
     * @return the RangeId
     */
    public Number getRangeId() {
        return (Number)getAttributeInternal(RANGEID);
    }

    /**
     * Sets <code>value</code> as the attribute value for RangeId.
     * @param value value to set the RangeId
     */
    public void setRangeId(Number value) {
        setAttributeInternal(RANGEID, value);
    }

    /**
     * Gets the attribute value for RangeoblineId, using the alias name RangeoblineId.
     * @return the RangeoblineId
     */
    public Number getRangeoblineId() {
        return (Number)getAttributeInternal(RANGEOBLINEID);
    }

    /**
     * Sets <code>value</code> as the attribute value for RangeoblineId.
     * @param value value to set the RangeoblineId
     */
    public void setRangeoblineId(Number value) {
        setAttributeInternal(RANGEOBLINEID, value);
    }

    /**
     * Gets the attribute value for SalesorderId, using the alias name SalesorderId.
     * @return the SalesorderId
     */
    public String getSalesorderId() {
        return (String)getAttributeInternal(SALESORDERID);
    }

    /**
     * Sets <code>value</code> as the attribute value for SalesorderId.
     * @param value value to set the SalesorderId
     */
    public void setSalesorderId(String value) {
        setAttributeInternal(SALESORDERID, value);
    }

    /**
     * Gets the attribute value for SolineId, using the alias name SolineId.
     * @return the SolineId
     */
    public Number getSolineId() {
        return (Number)getAttributeInternal(SOLINEID);
    }

    /**
     * Sets <code>value</code> as the attribute value for SolineId.
     * @param value value to set the SolineId
     */
    public void setSolineId(Number value) {
        setAttributeInternal(SOLINEID, value);
    }

    /**
     * Gets the attribute value for ItemCode, using the alias name ItemCode.
     * @return the ItemCode
     */
    public String getItemCode() {
        return (String)getAttributeInternal(ITEMCODE);
    }

    /**
     * Sets <code>value</code> as the attribute value for ItemCode.
     * @param value value to set the ItemCode
     */
    public void setItemCode(String value) {
        setAttributeInternal(ITEMCODE, value);
    }

    /**
     * Gets the attribute value for CutjobId, using the alias name CutjobId.
     * @return the CutjobId
     */
    public String getCutjobId() {
        return (String)getAttributeInternal(CUTJOBID);
    }

    /**
     * Sets <code>value</code> as the attribute value for CutjobId.
     * @param value value to set the CutjobId
     */
    public void setCutjobId(String value) {
        setAttributeInternal(CUTJOBID, value);
    }

    /**
     * Gets the attribute value for InseamId, using the alias name InseamId.
     * @return the InseamId
     */
    public String getInseamId() {
        return (String)getAttributeInternal(INSEAMID);
    }

    /**
     * Sets <code>value</code> as the attribute value for InseamId.
     * @param value value to set the InseamId
     */
    public void setInseamId(String value) {
        setAttributeInternal(INSEAMID, value);
    }

    /**
     * Gets the attribute value for Cuttingqty, using the alias name Cuttingqty.
     * @return the Cuttingqty
     */
    public Number getCuttingqty() {
        return (Number)getAttributeInternal(CUTTINGQTY);
    }

    /**
     * Sets <code>value</code> as the attribute value for Cuttingqty.
     * @param value value to set the Cuttingqty
     */
    public void setCuttingqty(Number value) {
        setAttributeInternal(CUTTINGQTY, value);
    }

    /**
     * Gets the attribute value for Rajqty, using the alias name Rajqty.
     * @return the Rajqty
     */
    public Number getRajqty() {
        return (Number)getAttributeInternal(RAJQTY);
    }

    /**
     * Sets <code>value</code> as the attribute value for Rajqty.
     * @param value value to set the Rajqty
     */
    public void setRajqty(Number value) {
        setAttributeInternal(RAJQTY, value);
    }

    /**
     * Gets the attribute value for FabCons, using the alias name FabCons.
     * @return the FabCons
     */
    public Number getFabCons() {
        return (Number)getAttributeInternal(FABCONS);
    }

    /**
     * Sets <code>value</code> as the attribute value for FabCons.
     * @param value value to set the FabCons
     */
    public void setFabCons(Number value) {
        setAttributeInternal(FABCONS, value);
    }

    /**
     * Gets the attribute value for LastUpdateDate, using the alias name LastUpdateDate.
     * @return the LastUpdateDate
     */
    public Date getLastUpdateDate() {
        return (Date)getAttributeInternal(LASTUPDATEDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for LastUpdateDate.
     * @param value value to set the LastUpdateDate
     */
    public void setLastUpdateDate(Date value) {
        setAttributeInternal(LASTUPDATEDATE, value);
    }

    /**
     * Gets the attribute value for LastUpdatedBy, using the alias name LastUpdatedBy.
     * @return the LastUpdatedBy
     */
    public Number getLastUpdatedBy() {
        return (Number)getAttributeInternal(LASTUPDATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for LastUpdatedBy.
     * @param value value to set the LastUpdatedBy
     */
    public void setLastUpdatedBy(Number value) {
        setAttributeInternal(LASTUPDATEDBY, value);
    }

    /**
     * Gets the attribute value for CreationDate, using the alias name CreationDate.
     * @return the CreationDate
     */
    public Date getCreationDate() {
        return (Date)getAttributeInternal(CREATIONDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreationDate.
     * @param value value to set the CreationDate
     */
    public void setCreationDate(Date value) {
        setAttributeInternal(CREATIONDATE, value);
    }

    /**
     * Gets the attribute value for CreatedBy, using the alias name CreatedBy.
     * @return the CreatedBy
     */
    public Number getCreatedBy() {
        return (Number)getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreatedBy.
     * @param value value to set the CreatedBy
     */
    public void setCreatedBy(Number value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for ObPosted, using the alias name ObPosted.
     * @return the ObPosted
     */
    public String getObPosted() {
        return (String)getAttributeInternal(OBPOSTED);
    }

    /**
     * Sets <code>value</code> as the attribute value for ObPosted.
     * @param value value to set the ObPosted
     */
    public void setObPosted(String value) {
        setAttributeInternal(OBPOSTED, value);
    }

    /**
     * Gets the attribute value for Obrefno, using the alias name Obrefno.
     * @return the Obrefno
     */
    public String getObrefno() {
        return (String)getAttributeInternal(OBREFNO);
    }

    /**
     * Sets <code>value</code> as the attribute value for Obrefno.
     * @param value value to set the Obrefno
     */
    public void setObrefno(String value) {
        setAttributeInternal(OBREFNO, value);
    }

    /**
     * Gets the attribute value for BlancQty, using the alias name BlancQty.
     * @return the BlancQty
     */
    public Number getBlancQty() {
        return (Number)getAttributeInternal(BLANCQTY);
    }

    /**
     * Sets <code>value</code> as the attribute value for BlancQty.
     * @param value value to set the BlancQty
     */
    public void setBlancQty(Number value) {
        setAttributeInternal(BLANCQTY, value);
    }

    /**
     * Gets the attribute value for ItemDescription, using the alias name ItemDescription.
     * @return the ItemDescription
     */
    public String getItemDescription() {
        return (String)getAttributeInternal(ITEMDESCRIPTION);
    }

    /**
     * Sets <code>value</code> as the attribute value for ItemDescription.
     * @param value value to set the ItemDescription
     */
    public void setItemDescription(String value) {
        setAttributeInternal(ITEMDESCRIPTION, value);
    }

    /**
     * Gets the attribute value for Orderqty, using the alias name Orderqty.
     * @return the Orderqty
     */
    public Number getOrderqty() {
        return (Number)getAttributeInternal(ORDERQTY);
    }

    /**
     * Sets <code>value</code> as the attribute value for Orderqty.
     * @param value value to set the Orderqty
     */
    public void setOrderqty(Number value) {
        setAttributeInternal(ORDERQTY, value);
    }

    /**
     * Gets the attribute value for QtyWithExtra, using the alias name QtyWithExtra.
     * @return the QtyWithExtra
     */
    public String getQtyWithExtra() {
        return (String)getAttributeInternal(QTYWITHEXTRA);
    }

    /**
     * Sets <code>value</code> as the attribute value for QtyWithExtra.
     * @param value value to set the QtyWithExtra
     */
    public void setQtyWithExtra(String value) {
        setAttributeInternal(QTYWITHEXTRA, value);
    }

    /**
     * Gets the attribute value for PreviousProduction, using the alias name PreviousProduction.
     * @return the PreviousProduction
     */
    public Number getPreviousProduction() {
        return (Number)getAttributeInternal(PREVIOUSPRODUCTION);
    }

    /**
     * Sets <code>value</code> as the attribute value for PreviousProduction.
     * @param value value to set the PreviousProduction
     */
    public void setPreviousProduction(Number value) {
        setAttributeInternal(PREVIOUSPRODUCTION, value);
    }

    /**
     * Gets the attribute value for BalanceProduction, using the alias name BalanceProduction.
     * @return the BalanceProduction
     */
    public Number getBalanceProduction() {
        return (Number)getAttributeInternal(BALANCEPRODUCTION);
    }

    /**
     * Sets <code>value</code> as the attribute value for BalanceProduction.
     * @param value value to set the BalanceProduction
     */
    public void setBalanceProduction(Number value) {
        setAttributeInternal(BALANCEPRODUCTION, value);
    }

    /**
     * Gets the attribute value for Production, using the alias name Production.
     * @return the Production
     */
    public Number getProduction() {
        return (Number)getAttributeInternal(PRODUCTION);
    }

    /**
     * Sets <code>value</code> as the attribute value for Production.
     * @param value value to set the Production
     */
    public void setProduction(Number value) {
        setAttributeInternal(PRODUCTION, value);
    }

    /**
     * Gets the attribute value for Attribute1, using the alias name Attribute1.
     * @return the Attribute1
     */
    public String getAttribute1() {
        return (String)getAttributeInternal(ATTRIBUTE1);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute1.
     * @param value value to set the Attribute1
     */
    public void setAttribute1(String value) {
        setAttributeInternal(ATTRIBUTE1, value);
    }

    /**
     * Gets the attribute value for Attribute2, using the alias name Attribute2.
     * @return the Attribute2
     */
    public String getAttribute2() {
        return (String)getAttributeInternal(ATTRIBUTE2);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute2.
     * @param value value to set the Attribute2
     */
    public void setAttribute2(String value) {
        setAttributeInternal(ATTRIBUTE2, value);
    }

    /**
     * Gets the attribute value for ErrorMessage, using the alias name ErrorMessage.
     * @return the ErrorMessage
     */
    public String getErrorMessage() {
        return (String)getAttributeInternal(ERRORMESSAGE);
    }

    /**
     * Sets <code>value</code> as the attribute value for ErrorMessage.
     * @param value value to set the ErrorMessage
     */
    public void setErrorMessage(String value) {
        setAttributeInternal(ERRORMESSAGE, value);
    }

    /**
     * Gets the attribute value for LastAction, using the alias name LastAction.
     * @return the LastAction
     */
    public String getLastAction() {
        return (String)getAttributeInternal(LASTACTION);
    }

    /**
     * Sets <code>value</code> as the attribute value for LastAction.
     * @param value value to set the LastAction
     */
    public void setLastAction(String value) {
        setAttributeInternal(LASTACTION, value);
    }

    /**
     * Gets the attribute value for BpoId, using the alias name BpoId.
     * @return the BpoId
     */
    public Number getBpoId() {
        return (Number)getAttributeInternal(BPOID);
    }

    /**
     * Sets <code>value</code> as the attribute value for BpoId.
     * @param value value to set the BpoId
     */
    public void setBpoId(Number value) {
        setAttributeInternal(BPOID, value);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }

    /**
     * @return the associated entity oracle.jbo.RowIterator.
     */
    public RowIterator getDetailEOtodetailEo() {
        return (RowIterator)getAttributeInternal(DETAILEOTODETAILEO);
    }

    /**
     * @return the associated entity oracle.jbo.RowIterator.
     */
    public RowIterator getBundleEO() {
        return (RowIterator)getAttributeInternal(BUNDLEEO);
    }


    /**
     * @return the associated entity HederEOImpl.
     */
    public HederEOImpl getHederEO() {
        return (HederEOImpl)getAttributeInternal(HEDEREO);
    }

    /**
     * Sets <code>value</code> as the associated entity HederEOImpl.
     */
    public void setHederEO(HederEOImpl value) {
        setAttributeInternal(HEDEREO, value);
    }


    /**
     * @param rangeId key constituent
     * @param rangeoblineId key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(Number rangeId, Number rangeoblineId) {
        return new Key(new Object[]{rangeId, rangeoblineId});
    }

    protected void create(AttributeList attributeList) {
        super.create(attributeList);
        Integer empno =Integer.parseInt(new oracle.jbo.server.SequenceImpl("MNJ_MFG_RANGE_OBLINE_S", getDBTransaction()).getSequenceNumber().toString());
           oracle.jbo.server.SequenceImpl s =new oracle.jbo.server.SequenceImpl("MNJ_MFG_RANGE_OBLINE_S",getDBTransaction());
           oracle.jbo.domain.Number sVal = s.getSequenceNumber();
           setRangeoblineId(sVal);
           //cust_mnj_ont_pkg.cust_mnj_packassort_srno
       //setRangeId(new oracle.jbo.domain.Number(getSrNoString()));
    }
    
    /**
         * Custom DML update/insert/delete logic here.
         * @param operation the operation type
         * @param e the transaction event
         */
        protected void doDML(int operation, TransactionEvent e) {
            Map sessionScope = ADFContext.getCurrent().getSessionScope();   
            String user = (String)sessionScope.get("userId");
            String orgId  =(String)sessionScope.get("orgId");
            String unitName  =(String)sessionScope.get("unitName");
            
            System.out.println("ASSES INS DO DML 1 ------------------>"+user);
            System.out.println("ASSES INS DO DML 2------------------>"+orgId);
            System.out.println("ASSES INS DML 3 ------------------>"+unitName);
            
            if(DML_UPDATE == operation){
                      try {
                          
                          setLastUpdateDate((Date)Date.getCurrentDate()); 
                          setLastUpdatedBy(new oracle.jbo.domain.Number(user));
                      } catch (SQLException f) {
                          System.out.println(f.getMessage());
                      }
                  }
                  else if (DML_INSERT == operation){
                   
                      try {
                          
                          //setHeaderNo(getSrNoString());
                          //setOrgId(new oracle.jbo.domain.Number(orgId));
                          //setAttribute1(unitName);
                          setCreationDate((Date)Date.getCurrentDate());  
                          setCreatedBy(new oracle.jbo.domain.Number(user));
                         
                         
                         
                      } catch (SQLException f) {
                          ;
                      }
                  } 
            
            super.doDML(operation, e);
        }

}
