package mnj.ont.model.entities;

import oracle.jbo.AttributeList;
import oracle.jbo.Key;
import oracle.jbo.RowIterator;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.TransactionEvent;


import java.sql.SQLException;

import java.util.Map;


import oracle.adf.share.ADFContext;


// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Feb 26 16:48:47 PKT 2015
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class HederEOImpl extends EntityImpl {
    private static EntityDefImpl mDefinitionObject;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. Do not modify.
     */
    public enum AttributesEnum {
        DivisionId {
            public Object get(HederEOImpl obj) {
                return obj.getDivisionId();
            }

            public void put(HederEOImpl obj, Object value) {
                obj.setDivisionId((String)value);
            }
        }
        ,
        RangeId {
            public Object get(HederEOImpl obj) {
                return obj.getRangeId();
            }

            public void put(HederEOImpl obj, Object value) {
                obj.setRangeId((Number)value);
            }
        }
        ,
        RangeNumber {
            public Object get(HederEOImpl obj) {
                return obj.getRangeNumber();
            }

            public void put(HederEOImpl obj, Object value) {
                obj.setRangeNumber((Number)value);
            }
        }
        ,
        RangeDate {
            public Object get(HederEOImpl obj) {
                return obj.getRangeDate();
            }

            public void put(HederEOImpl obj, Object value) {
                obj.setRangeDate((Date)value);
            }
        }
        ,
        RatioplanId {
            public Object get(HederEOImpl obj) {
                return obj.getRatioplanId();
            }

            public void put(HederEOImpl obj, Object value) {
                obj.setRatioplanId((Number)value);
            }
        }
        ,
        RatioplanNumber {
            public Object get(HederEOImpl obj) {
                return obj.getRatioplanNumber();
            }

            public void put(HederEOImpl obj, Object value) {
                obj.setRatioplanNumber((Number)value);
            }
        }
        ,
        PlylineId {
            public Object get(HederEOImpl obj) {
                return obj.getPlylineId();
            }

            public void put(HederEOImpl obj, Object value) {
                obj.setPlylineId((Number)value);
            }
        }
        ,
        RangrefNo {
            public Object get(HederEOImpl obj) {
                return obj.getRangrefNo();
            }

            public void put(HederEOImpl obj, Object value) {
                obj.setRangrefNo((String)value);
            }
        }
        ,
        CuttingType {
            public Object get(HederEOImpl obj) {
                return obj.getCuttingType();
            }

            public void put(HederEOImpl obj, Object value) {
                obj.setCuttingType((String)value);
            }
        }
        ,
        SalesorderId {
            public Object get(HederEOImpl obj) {
                return obj.getSalesorderId();
            }

            public void put(HederEOImpl obj, Object value) {
                obj.setSalesorderId((Number)value);
            }
        }
        ,
        SolineId {
            public Object get(HederEOImpl obj) {
                return obj.getSolineId();
            }

            public void put(HederEOImpl obj, Object value) {
                obj.setSolineId((Number)value);
            }
        }
        ,
        FgItemcode {
            public Object get(HederEOImpl obj) {
                return obj.getFgItemcode();
            }

            public void put(HederEOImpl obj, Object value) {
                obj.setFgItemcode((String)value);
            }
        }
        ,
        ComponentId {
            public Object get(HederEOImpl obj) {
                return obj.getComponentId();
            }

            public void put(HederEOImpl obj, Object value) {
                obj.setComponentId((String)value);
            }
        }
        ,
        FreshRange {
            public Object get(HederEOImpl obj) {
                return obj.getFreshRange();
            }

            public void put(HederEOImpl obj, Object value) {
                obj.setFreshRange((String)value);
            }
        }
        ,
        CutPcs {
            public Object get(HederEOImpl obj) {
                return obj.getCutPcs();
            }

            public void put(HederEOImpl obj, Object value) {
                obj.setCutPcs((String)value);
            }
        }
        ,
        Cut {
            public Object get(HederEOImpl obj) {
                return obj.getCut();
            }

            public void put(HederEOImpl obj, Object value) {
                obj.setCut((String)value);
            }
        }
        ,
        Fold {
            public Object get(HederEOImpl obj) {
                return obj.getFold();
            }

            public void put(HederEOImpl obj, Object value) {
                obj.setFold((String)value);
            }
        }
        ,
        RpForId {
            public Object get(HederEOImpl obj) {
                return obj.getRpForId();
            }

            public void put(HederEOImpl obj, Object value) {
                obj.setRpForId((String)value);
            }
        }
        ,
        ExtraCutting {
            public Object get(HederEOImpl obj) {
                return obj.getExtraCutting();
            }

            public void put(HederEOImpl obj, Object value) {
                obj.setExtraCutting((String)value);
            }
        }
        ,
        SpreaderId {
            public Object get(HederEOImpl obj) {
                return obj.getSpreaderId();
            }

            public void put(HederEOImpl obj, Object value) {
                obj.setSpreaderId((String)value);
            }
        }
        ,
        ContId {
            public Object get(HederEOImpl obj) {
                return obj.getContId();
            }

            public void put(HederEOImpl obj, Object value) {
                obj.setContId((String)value);
            }
        }
        ,
        ContractorName {
            public Object get(HederEOImpl obj) {
                return obj.getContractorName();
            }

            public void put(HederEOImpl obj, Object value) {
                obj.setContractorName((String)value);
            }
        }
        ,
        TotalPly {
            public Object get(HederEOImpl obj) {
                return obj.getTotalPly();
            }

            public void put(HederEOImpl obj, Object value) {
                obj.setTotalPly((Number)value);
            }
        }
        ,
        TotalPlyRej {
            public Object get(HederEOImpl obj) {
                return obj.getTotalPlyRej();
            }

            public void put(HederEOImpl obj, Object value) {
                obj.setTotalPlyRej((Number)value);
            }
        }
        ,
        TotalRatio {
            public Object get(HederEOImpl obj) {
                return obj.getTotalRatio();
            }

            public void put(HederEOImpl obj, Object value) {
                obj.setTotalRatio((Number)value);
            }
        }
        ,
        FabricWidth {
            public Object get(HederEOImpl obj) {
                return obj.getFabricWidth();
            }

            public void put(HederEOImpl obj, Object value) {
                obj.setFabricWidth((Number)value);
            }
        }
        ,
        FabricPattern {
            public Object get(HederEOImpl obj) {
                return obj.getFabricPattern();
            }

            public void put(HederEOImpl obj, Object value) {
                obj.setFabricPattern((String)value);
            }
        }
        ,
        MarkerLength {
            public Object get(HederEOImpl obj) {
                return obj.getMarkerLength();
            }

            public void put(HederEOImpl obj, Object value) {
                obj.setMarkerLength((Number)value);
            }
        }
        ,
        CF {
            public Object get(HederEOImpl obj) {
                return obj.getCF();
            }

            public void put(HederEOImpl obj, Object value) {
                obj.setCF((Number)value);
            }
        }
        ,
        ExtraMtr {
            public Object get(HederEOImpl obj) {
                return obj.getExtraMtr();
            }

            public void put(HederEOImpl obj, Object value) {
                obj.setExtraMtr((Number)value);
            }
        }
        ,
        PostedStatus {
            public Object get(HederEOImpl obj) {
                return obj.getPostedStatus();
            }

            public void put(HederEOImpl obj, Object value) {
                obj.setPostedStatus((String)value);
            }
        }
        ,
        PostedDate {
            public Object get(HederEOImpl obj) {
                return obj.getPostedDate();
            }

            public void put(HederEOImpl obj, Object value) {
                obj.setPostedDate((Date)value);
            }
        }
        ,
        SprConTypeId {
            public Object get(HederEOImpl obj) {
                return obj.getSprConTypeId();
            }

            public void put(HederEOImpl obj, Object value) {
                obj.setSprConTypeId((String)value);
            }
        }
        ,
        SprContractorId {
            public Object get(HederEOImpl obj) {
                return obj.getSprContractorId();
            }

            public void put(HederEOImpl obj, Object value) {
                obj.setSprContractorId((String)value);
            }
        }
        ,
        CutConTypeId {
            public Object get(HederEOImpl obj) {
                return obj.getCutConTypeId();
            }

            public void put(HederEOImpl obj, Object value) {
                obj.setCutConTypeId((String)value);
            }
        }
        ,
        CutContractorId {
            public Object get(HederEOImpl obj) {
                return obj.getCutContractorId();
            }

            public void put(HederEOImpl obj, Object value) {
                obj.setCutContractorId((String)value);
            }
        }
        ,
        NumConTypeId {
            public Object get(HederEOImpl obj) {
                return obj.getNumConTypeId();
            }

            public void put(HederEOImpl obj, Object value) {
                obj.setNumConTypeId((String)value);
            }
        }
        ,
        NumContractorId {
            public Object get(HederEOImpl obj) {
                return obj.getNumContractorId();
            }

            public void put(HederEOImpl obj, Object value) {
                obj.setNumContractorId((String)value);
            }
        }
        ,
        FabricType {
            public Object get(HederEOImpl obj) {
                return obj.getFabricType();
            }

            public void put(HederEOImpl obj, Object value) {
                obj.setFabricType((String)value);
            }
        }
        ,
        Paymentlock {
            public Object get(HederEOImpl obj) {
                return obj.getPaymentlock();
            }

            public void put(HederEOImpl obj, Object value) {
                obj.setPaymentlock((String)value);
            }
        }
        ,
        LastUpdateDate {
            public Object get(HederEOImpl obj) {
                return obj.getLastUpdateDate();
            }

            public void put(HederEOImpl obj, Object value) {
                obj.setLastUpdateDate((Date)value);
            }
        }
        ,
        LastUpdatedBy {
            public Object get(HederEOImpl obj) {
                return obj.getLastUpdatedBy();
            }

            public void put(HederEOImpl obj, Object value) {
                obj.setLastUpdatedBy((Number)value);
            }
        }
        ,
        CreationDate {
            public Object get(HederEOImpl obj) {
                return obj.getCreationDate();
            }

            public void put(HederEOImpl obj, Object value) {
                obj.setCreationDate((Date)value);
            }
        }
        ,
        CreatedBy {
            public Object get(HederEOImpl obj) {
                return obj.getCreatedBy();
            }

            public void put(HederEOImpl obj, Object value) {
                obj.setCreatedBy((Number)value);
            }
        }
        ,
        PrrangeDate {
            public Object get(HederEOImpl obj) {
                return obj.getPrrangeDate();
            }

            public void put(HederEOImpl obj, Object value) {
                obj.setPrrangeDate((Date)value);
            }
        }
        ,
        CuttingDate {
            public Object get(HederEOImpl obj) {
                return obj.getCuttingDate();
            }

            public void put(HederEOImpl obj, Object value) {
                obj.setCuttingDate((Date)value);
            }
        }
        ,
        NumberingDate {
            public Object get(HederEOImpl obj) {
                return obj.getNumberingDate();
            }

            public void put(HederEOImpl obj, Object value) {
                obj.setNumberingDate((Date)value);
            }
        }
        ,
        RangePosted {
            public Object get(HederEOImpl obj) {
                return obj.getRangePosted();
            }

            public void put(HederEOImpl obj, Object value) {
                obj.setRangePosted((String)value);
            }
        }
        ,
        CuttPosted {
            public Object get(HederEOImpl obj) {
                return obj.getCuttPosted();
            }

            public void put(HederEOImpl obj, Object value) {
                obj.setCuttPosted((String)value);
            }
        }
        ,
        NumPosted {
            public Object get(HederEOImpl obj) {
                return obj.getNumPosted();
            }

            public void put(HederEOImpl obj, Object value) {
                obj.setNumPosted((String)value);
            }
        }
        ,
        InspDate {
            public Object get(HederEOImpl obj) {
                return obj.getInspDate();
            }

            public void put(HederEOImpl obj, Object value) {
                obj.setInspDate((Date)value);
            }
        }
        ,
        InspRemarks {
            public Object get(HederEOImpl obj) {
                return obj.getInspRemarks();
            }

            public void put(HederEOImpl obj, Object value) {
                obj.setInspRemarks((String)value);
            }
        }
        ,
        IssueStatus {
            public Object get(HederEOImpl obj) {
                return obj.getIssueStatus();
            }

            public void put(HederEOImpl obj, Object value) {
                obj.setIssueStatus((String)value);
            }
        }
        ,
        CompleteStatus {
            public Object get(HederEOImpl obj) {
                return obj.getCompleteStatus();
            }

            public void put(HederEOImpl obj, Object value) {
                obj.setCompleteStatus((String)value);
            }
        }
        ,
        Subinventory {
            public Object get(HederEOImpl obj) {
                return obj.getSubinventory();
            }

            public void put(HederEOImpl obj, Object value) {
                obj.setSubinventory((String)value);
            }
        }
        ,
        VrfyPost {
            public Object get(HederEOImpl obj) {
                return obj.getVrfyPost();
            }

            public void put(HederEOImpl obj, Object value) {
                obj.setVrfyPost((String)value);
            }
        }
        ,
        CuttPostedTmp {
            public Object get(HederEOImpl obj) {
                return obj.getCuttPostedTmp();
            }

            public void put(HederEOImpl obj, Object value) {
                obj.setCuttPostedTmp((String)value);
            }
        }
        ,
        NumPostedTmp {
            public Object get(HederEOImpl obj) {
                return obj.getNumPostedTmp();
            }

            public void put(HederEOImpl obj, Object value) {
                obj.setNumPostedTmp((String)value);
            }
        }
        ,
        RangePostedTmp {
            public Object get(HederEOImpl obj) {
                return obj.getRangePostedTmp();
            }

            public void put(HederEOImpl obj, Object value) {
                obj.setRangePostedTmp((String)value);
            }
        }
        ,
        CompleteStatusTmp {
            public Object get(HederEOImpl obj) {
                return obj.getCompleteStatusTmp();
            }

            public void put(HederEOImpl obj, Object value) {
                obj.setCompleteStatusTmp((String)value);
            }
        }
        ,
        CutInchargeId {
            public Object get(HederEOImpl obj) {
                return obj.getCutInchargeId();
            }

            public void put(HederEOImpl obj, Object value) {
                obj.setCutInchargeId((String)value);
            }
        }
        ,
        NumStatus {
            public Object get(HederEOImpl obj) {
                return obj.getNumStatus();
            }

            public void put(HederEOImpl obj, Object value) {
                obj.setNumStatus((String)value);
            }
        }
        ,
        LastUpdateLogin {
            public Object get(HederEOImpl obj) {
                return obj.getLastUpdateLogin();
            }

            public void put(HederEOImpl obj, Object value) {
                obj.setLastUpdateLogin((Number)value);
            }
        }
        ,
        Attribute1 {
            public Object get(HederEOImpl obj) {
                return obj.getAttribute1();
            }

            public void put(HederEOImpl obj, Object value) {
                obj.setAttribute1((String)value);
            }
        }
        ,
        Attribute2 {
            public Object get(HederEOImpl obj) {
                return obj.getAttribute2();
            }

            public void put(HederEOImpl obj, Object value) {
                obj.setAttribute2((String)value);
            }
        }
        ,
        Attribute3 {
            public Object get(HederEOImpl obj) {
                return obj.getAttribute3();
            }

            public void put(HederEOImpl obj, Object value) {
                obj.setAttribute3((String)value);
            }
        }
        ,
        Attribute4 {
            public Object get(HederEOImpl obj) {
                return obj.getAttribute4();
            }

            public void put(HederEOImpl obj, Object value) {
                obj.setAttribute4((String)value);
            }
        }
        ,
        Attribute5 {
            public Object get(HederEOImpl obj) {
                return obj.getAttribute5();
            }

            public void put(HederEOImpl obj, Object value) {
                obj.setAttribute5((String)value);
            }
        }
        ,
        Attribute6 {
            public Object get(HederEOImpl obj) {
                return obj.getAttribute6();
            }

            public void put(HederEOImpl obj, Object value) {
                obj.setAttribute6((String)value);
            }
        }
        ,
        Attribute7 {
            public Object get(HederEOImpl obj) {
                return obj.getAttribute7();
            }

            public void put(HederEOImpl obj, Object value) {
                obj.setAttribute7((String)value);
            }
        }
        ,
        Attribute8 {
            public Object get(HederEOImpl obj) {
                return obj.getAttribute8();
            }

            public void put(HederEOImpl obj, Object value) {
                obj.setAttribute8((String)value);
            }
        }
        ,
        Attribute9 {
            public Object get(HederEOImpl obj) {
                return obj.getAttribute9();
            }

            public void put(HederEOImpl obj, Object value) {
                obj.setAttribute9((String)value);
            }
        }
        ,
        Attribute10 {
            public Object get(HederEOImpl obj) {
                return obj.getAttribute10();
            }

            public void put(HederEOImpl obj, Object value) {
                obj.setAttribute10((String)value);
            }
        }
        ,
        Attribute11 {
            public Object get(HederEOImpl obj) {
                return obj.getAttribute11();
            }

            public void put(HederEOImpl obj, Object value) {
                obj.setAttribute11((String)value);
            }
        }
        ,
        Attribute12 {
            public Object get(HederEOImpl obj) {
                return obj.getAttribute12();
            }

            public void put(HederEOImpl obj, Object value) {
                obj.setAttribute12((String)value);
            }
        }
        ,
        Attribute13 {
            public Object get(HederEOImpl obj) {
                return obj.getAttribute13();
            }

            public void put(HederEOImpl obj, Object value) {
                obj.setAttribute13((String)value);
            }
        }
        ,
        Attribute14 {
            public Object get(HederEOImpl obj) {
                return obj.getAttribute14();
            }

            public void put(HederEOImpl obj, Object value) {
                obj.setAttribute14((String)value);
            }
        }
        ,
        Attribute15 {
            public Object get(HederEOImpl obj) {
                return obj.getAttribute15();
            }

            public void put(HederEOImpl obj, Object value) {
                obj.setAttribute15((String)value);
            }
        }
        ,
        BuyerId {
            public Object get(HederEOImpl obj) {
                return obj.getBuyerId();
            }

            public void put(HederEOImpl obj, Object value) {
                obj.setBuyerId((Number)value);
            }
        }
        ,
        Style {
            public Object get(HederEOImpl obj) {
                return obj.getStyle();
            }

            public void put(HederEOImpl obj, Object value) {
                obj.setStyle((String)value);
            }
        }
        ,
        OrderQty {
            public Object get(HederEOImpl obj) {
                return obj.getOrderQty();
            }

            public void put(HederEOImpl obj, Object value) {
                obj.setOrderQty((Number)value);
            }
        }
        ,
        Stn {
            public Object get(HederEOImpl obj) {
                return obj.getStn();
            }

            public void put(HederEOImpl obj, Object value) {
                obj.setStn((String)value);
            }
        }
        ,
        BpoNo {
            public Object get(HederEOImpl obj) {
                return obj.getBpoNo();
            }

            public void put(HederEOImpl obj, Object value) {
                obj.setBpoNo((String)value);
            }
        }
        ,
        Season {
            public Object get(HederEOImpl obj) {
                return obj.getSeason();
            }

            public void put(HederEOImpl obj, Object value) {
                obj.setSeason((String)value);
            }
        }
        ,
        PocId {
            public Object get(HederEOImpl obj) {
                return obj.getPocId();
            }

            public void put(HederEOImpl obj, Object value) {
                obj.setPocId((Number)value);
            }
        }
        ,
        LineEO {
            public Object get(HederEOImpl obj) {
                return obj.getLineEO();
            }

            public void put(HederEOImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        DetailEO {
            public Object get(HederEOImpl obj) {
                return obj.getDetailEO();
            }

            public void put(HederEOImpl obj, Object value) {
                obj.setDetailEO((DetailEOImpl)value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static int firstIndex = 0;

        public abstract Object get(HederEOImpl object);

        public abstract void put(HederEOImpl object, Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int DIVISIONID = AttributesEnum.DivisionId.index();
    public static final int RANGEID = AttributesEnum.RangeId.index();
    public static final int RANGENUMBER = AttributesEnum.RangeNumber.index();
    public static final int RANGEDATE = AttributesEnum.RangeDate.index();
    public static final int RATIOPLANID = AttributesEnum.RatioplanId.index();
    public static final int RATIOPLANNUMBER = AttributesEnum.RatioplanNumber.index();
    public static final int PLYLINEID = AttributesEnum.PlylineId.index();
    public static final int RANGREFNO = AttributesEnum.RangrefNo.index();
    public static final int CUTTINGTYPE = AttributesEnum.CuttingType.index();
    public static final int SALESORDERID = AttributesEnum.SalesorderId.index();
    public static final int SOLINEID = AttributesEnum.SolineId.index();
    public static final int FGITEMCODE = AttributesEnum.FgItemcode.index();
    public static final int COMPONENTID = AttributesEnum.ComponentId.index();
    public static final int FRESHRANGE = AttributesEnum.FreshRange.index();
    public static final int CUTPCS = AttributesEnum.CutPcs.index();
    public static final int CUT = AttributesEnum.Cut.index();
    public static final int FOLD = AttributesEnum.Fold.index();
    public static final int RPFORID = AttributesEnum.RpForId.index();
    public static final int EXTRACUTTING = AttributesEnum.ExtraCutting.index();
    public static final int SPREADERID = AttributesEnum.SpreaderId.index();
    public static final int CONTID = AttributesEnum.ContId.index();
    public static final int CONTRACTORNAME = AttributesEnum.ContractorName.index();
    public static final int TOTALPLY = AttributesEnum.TotalPly.index();
    public static final int TOTALPLYREJ = AttributesEnum.TotalPlyRej.index();
    public static final int TOTALRATIO = AttributesEnum.TotalRatio.index();
    public static final int FABRICWIDTH = AttributesEnum.FabricWidth.index();
    public static final int FABRICPATTERN = AttributesEnum.FabricPattern.index();
    public static final int MARKERLENGTH = AttributesEnum.MarkerLength.index();
    public static final int CF = AttributesEnum.CF.index();
    public static final int EXTRAMTR = AttributesEnum.ExtraMtr.index();
    public static final int POSTEDSTATUS = AttributesEnum.PostedStatus.index();
    public static final int POSTEDDATE = AttributesEnum.PostedDate.index();
    public static final int SPRCONTYPEID = AttributesEnum.SprConTypeId.index();
    public static final int SPRCONTRACTORID = AttributesEnum.SprContractorId.index();
    public static final int CUTCONTYPEID = AttributesEnum.CutConTypeId.index();
    public static final int CUTCONTRACTORID = AttributesEnum.CutContractorId.index();
    public static final int NUMCONTYPEID = AttributesEnum.NumConTypeId.index();
    public static final int NUMCONTRACTORID = AttributesEnum.NumContractorId.index();
    public static final int FABRICTYPE = AttributesEnum.FabricType.index();
    public static final int PAYMENTLOCK = AttributesEnum.Paymentlock.index();
    public static final int LASTUPDATEDATE = AttributesEnum.LastUpdateDate.index();
    public static final int LASTUPDATEDBY = AttributesEnum.LastUpdatedBy.index();
    public static final int CREATIONDATE = AttributesEnum.CreationDate.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int PRRANGEDATE = AttributesEnum.PrrangeDate.index();
    public static final int CUTTINGDATE = AttributesEnum.CuttingDate.index();
    public static final int NUMBERINGDATE = AttributesEnum.NumberingDate.index();
    public static final int RANGEPOSTED = AttributesEnum.RangePosted.index();
    public static final int CUTTPOSTED = AttributesEnum.CuttPosted.index();
    public static final int NUMPOSTED = AttributesEnum.NumPosted.index();
    public static final int INSPDATE = AttributesEnum.InspDate.index();
    public static final int INSPREMARKS = AttributesEnum.InspRemarks.index();
    public static final int ISSUESTATUS = AttributesEnum.IssueStatus.index();
    public static final int COMPLETESTATUS = AttributesEnum.CompleteStatus.index();
    public static final int SUBINVENTORY = AttributesEnum.Subinventory.index();
    public static final int VRFYPOST = AttributesEnum.VrfyPost.index();
    public static final int CUTTPOSTEDTMP = AttributesEnum.CuttPostedTmp.index();
    public static final int NUMPOSTEDTMP = AttributesEnum.NumPostedTmp.index();
    public static final int RANGEPOSTEDTMP = AttributesEnum.RangePostedTmp.index();
    public static final int COMPLETESTATUSTMP = AttributesEnum.CompleteStatusTmp.index();
    public static final int CUTINCHARGEID = AttributesEnum.CutInchargeId.index();
    public static final int NUMSTATUS = AttributesEnum.NumStatus.index();
    public static final int LASTUPDATELOGIN = AttributesEnum.LastUpdateLogin.index();
    public static final int ATTRIBUTE1 = AttributesEnum.Attribute1.index();
    public static final int ATTRIBUTE2 = AttributesEnum.Attribute2.index();
    public static final int ATTRIBUTE3 = AttributesEnum.Attribute3.index();
    public static final int ATTRIBUTE4 = AttributesEnum.Attribute4.index();
    public static final int ATTRIBUTE5 = AttributesEnum.Attribute5.index();
    public static final int ATTRIBUTE6 = AttributesEnum.Attribute6.index();
    public static final int ATTRIBUTE7 = AttributesEnum.Attribute7.index();
    public static final int ATTRIBUTE8 = AttributesEnum.Attribute8.index();
    public static final int ATTRIBUTE9 = AttributesEnum.Attribute9.index();
    public static final int ATTRIBUTE10 = AttributesEnum.Attribute10.index();
    public static final int ATTRIBUTE11 = AttributesEnum.Attribute11.index();
    public static final int ATTRIBUTE12 = AttributesEnum.Attribute12.index();
    public static final int ATTRIBUTE13 = AttributesEnum.Attribute13.index();
    public static final int ATTRIBUTE14 = AttributesEnum.Attribute14.index();
    public static final int ATTRIBUTE15 = AttributesEnum.Attribute15.index();
    public static final int BUYERID = AttributesEnum.BuyerId.index();
    public static final int STYLE = AttributesEnum.Style.index();
    public static final int ORDERQTY = AttributesEnum.OrderQty.index();
    public static final int STN = AttributesEnum.Stn.index();
    public static final int BPONO = AttributesEnum.BpoNo.index();
    public static final int SEASON = AttributesEnum.Season.index();
    public static final int POCID = AttributesEnum.PocId.index();
    public static final int LINEEO = AttributesEnum.LineEO.index();
    public static final int DETAILEO = AttributesEnum.DetailEO.index();

    /**
     * This is the default constructor (do not remove).
     */
    public HederEOImpl() {
    }


    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        if (mDefinitionObject == null) {
            mDefinitionObject = EntityDefImpl.findDefObject("mnj.ont.model.entities.HederEO");
        }
        return mDefinitionObject;
    }

    /**
     * Gets the attribute value for DivisionId, using the alias name DivisionId.
     * @return the DivisionId
     */
    public String getDivisionId() {
        return (String)getAttributeInternal(DIVISIONID);
    }

    /**
     * Sets <code>value</code> as the attribute value for DivisionId.
     * @param value value to set the DivisionId
     */
    public void setDivisionId(String value) {
        setAttributeInternal(DIVISIONID, value);
    }

    /**
     * Gets the attribute value for RangeId, using the alias name RangeId.
     * @return the RangeId
     */
    public Number getRangeId() {
        return (Number)getAttributeInternal(RANGEID);
    }

    /**
     * Sets <code>value</code> as the attribute value for RangeId.
     * @param value value to set the RangeId
     */
    public void setRangeId(Number value) {
        setAttributeInternal(RANGEID, value);
    }

    /**
     * Gets the attribute value for RangeNumber, using the alias name RangeNumber.
     * @return the RangeNumber
     */
    public Number getRangeNumber() {
        return (Number)getAttributeInternal(RANGENUMBER);
    }

    /**
     * Sets <code>value</code> as the attribute value for RangeNumber.
     * @param value value to set the RangeNumber
     */
    public void setRangeNumber(Number value) {
        setAttributeInternal(RANGENUMBER, value);
    }

    /**
     * Gets the attribute value for RangeDate, using the alias name RangeDate.
     * @return the RangeDate
     */
    public Date getRangeDate() {
        return (Date)getAttributeInternal(RANGEDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for RangeDate.
     * @param value value to set the RangeDate
     */
    public void setRangeDate(Date value) {
        setAttributeInternal(RANGEDATE, value);
    }

    /**
     * Gets the attribute value for RatioplanId, using the alias name RatioplanId.
     * @return the RatioplanId
     */
    public Number getRatioplanId() {
        return (Number)getAttributeInternal(RATIOPLANID);
    }

    /**
     * Sets <code>value</code> as the attribute value for RatioplanId.
     * @param value value to set the RatioplanId
     */
    public void setRatioplanId(Number value) {
        setAttributeInternal(RATIOPLANID, value);
    }

    /**
     * Gets the attribute value for RatioplanNumber, using the alias name RatioplanNumber.
     * @return the RatioplanNumber
     */
    public Number getRatioplanNumber() {
        return (Number)getAttributeInternal(RATIOPLANNUMBER);
    }

    /**
     * Sets <code>value</code> as the attribute value for RatioplanNumber.
     * @param value value to set the RatioplanNumber
     */
    public void setRatioplanNumber(Number value) {
        setAttributeInternal(RATIOPLANNUMBER, value);
    }

    /**
     * Gets the attribute value for PlylineId, using the alias name PlylineId.
     * @return the PlylineId
     */
    public Number getPlylineId() {
        return (Number)getAttributeInternal(PLYLINEID);
    }

    /**
     * Sets <code>value</code> as the attribute value for PlylineId.
     * @param value value to set the PlylineId
     */
    public void setPlylineId(Number value) {
        setAttributeInternal(PLYLINEID, value);
    }

    /**
     * Gets the attribute value for RangrefNo, using the alias name RangrefNo.
     * @return the RangrefNo
     */
    public String getRangrefNo() {
        return (String)getAttributeInternal(RANGREFNO);
    }

    /**
     * Sets <code>value</code> as the attribute value for RangrefNo.
     * @param value value to set the RangrefNo
     */
    public void setRangrefNo(String value) {
        setAttributeInternal(RANGREFNO, value);
    }

    /**
     * Gets the attribute value for CuttingType, using the alias name CuttingType.
     * @return the CuttingType
     */
    public String getCuttingType() {
        return (String)getAttributeInternal(CUTTINGTYPE);
    }

    /**
     * Sets <code>value</code> as the attribute value for CuttingType.
     * @param value value to set the CuttingType
     */
    public void setCuttingType(String value) {
        setAttributeInternal(CUTTINGTYPE, value);
    }

    /**
     * Gets the attribute value for SalesorderId, using the alias name SalesorderId.
     * @return the SalesorderId
     */
    public Number getSalesorderId() {
        return (Number)getAttributeInternal(SALESORDERID);
    }

    /**
     * Sets <code>value</code> as the attribute value for SalesorderId.
     * @param value value to set the SalesorderId
     */
    public void setSalesorderId(Number value) {
        setAttributeInternal(SALESORDERID, value);
    }

    /**
     * Gets the attribute value for SolineId, using the alias name SolineId.
     * @return the SolineId
     */
    public Number getSolineId() {
        return (Number)getAttributeInternal(SOLINEID);
    }

    /**
     * Sets <code>value</code> as the attribute value for SolineId.
     * @param value value to set the SolineId
     */
    public void setSolineId(Number value) {
        setAttributeInternal(SOLINEID, value);
    }

    /**
     * Gets the attribute value for FgItemcode, using the alias name FgItemcode.
     * @return the FgItemcode
     */
    public String getFgItemcode() {
        return (String)getAttributeInternal(FGITEMCODE);
    }

    /**
     * Sets <code>value</code> as the attribute value for FgItemcode.
     * @param value value to set the FgItemcode
     */
    public void setFgItemcode(String value) {
        setAttributeInternal(FGITEMCODE, value);
    }

    /**
     * Gets the attribute value for ComponentId, using the alias name ComponentId.
     * @return the ComponentId
     */
    public String getComponentId() {
        return (String)getAttributeInternal(COMPONENTID);
    }

    /**
     * Sets <code>value</code> as the attribute value for ComponentId.
     * @param value value to set the ComponentId
     */
    public void setComponentId(String value) {
        setAttributeInternal(COMPONENTID, value);
    }

    /**
     * Gets the attribute value for FreshRange, using the alias name FreshRange.
     * @return the FreshRange
     */
    public String getFreshRange() {
        return (String)getAttributeInternal(FRESHRANGE);
    }

    /**
     * Sets <code>value</code> as the attribute value for FreshRange.
     * @param value value to set the FreshRange
     */
    public void setFreshRange(String value) {
        setAttributeInternal(FRESHRANGE, value);
    }

    /**
     * Gets the attribute value for CutPcs, using the alias name CutPcs.
     * @return the CutPcs
     */
    public String getCutPcs() {
        return (String)getAttributeInternal(CUTPCS);
    }

    /**
     * Sets <code>value</code> as the attribute value for CutPcs.
     * @param value value to set the CutPcs
     */
    public void setCutPcs(String value) {
        setAttributeInternal(CUTPCS, value);
    }

    /**
     * Gets the attribute value for Cut, using the alias name Cut.
     * @return the Cut
     */
    public String getCut() {
        return (String)getAttributeInternal(CUT);
    }

    /**
     * Sets <code>value</code> as the attribute value for Cut.
     * @param value value to set the Cut
     */
    public void setCut(String value) {
        setAttributeInternal(CUT, value);
    }

    /**
     * Gets the attribute value for Fold, using the alias name Fold.
     * @return the Fold
     */
    public String getFold() {
        return (String)getAttributeInternal(FOLD);
    }

    /**
     * Sets <code>value</code> as the attribute value for Fold.
     * @param value value to set the Fold
     */
    public void setFold(String value) {
        setAttributeInternal(FOLD, value);
    }

    /**
     * Gets the attribute value for RpForId, using the alias name RpForId.
     * @return the RpForId
     */
    public String getRpForId() {
        return (String)getAttributeInternal(RPFORID);
    }

    /**
     * Sets <code>value</code> as the attribute value for RpForId.
     * @param value value to set the RpForId
     */
    public void setRpForId(String value) {
        setAttributeInternal(RPFORID, value);
    }

    /**
     * Gets the attribute value for ExtraCutting, using the alias name ExtraCutting.
     * @return the ExtraCutting
     */
    public String getExtraCutting() {
        return (String)getAttributeInternal(EXTRACUTTING);
    }

    /**
     * Sets <code>value</code> as the attribute value for ExtraCutting.
     * @param value value to set the ExtraCutting
     */
    public void setExtraCutting(String value) {
        setAttributeInternal(EXTRACUTTING, value);
    }

    /**
     * Gets the attribute value for SpreaderId, using the alias name SpreaderId.
     * @return the SpreaderId
     */
    public String getSpreaderId() {
        return (String)getAttributeInternal(SPREADERID);
    }

    /**
     * Sets <code>value</code> as the attribute value for SpreaderId.
     * @param value value to set the SpreaderId
     */
    public void setSpreaderId(String value) {
        setAttributeInternal(SPREADERID, value);
    }

    /**
     * Gets the attribute value for ContId, using the alias name ContId.
     * @return the ContId
     */
    public String getContId() {
        return (String)getAttributeInternal(CONTID);
    }

    /**
     * Sets <code>value</code> as the attribute value for ContId.
     * @param value value to set the ContId
     */
    public void setContId(String value) {
        setAttributeInternal(CONTID, value);
    }

    /**
     * Gets the attribute value for ContractorName, using the alias name ContractorName.
     * @return the ContractorName
     */
    public String getContractorName() {
        return (String)getAttributeInternal(CONTRACTORNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for ContractorName.
     * @param value value to set the ContractorName
     */
    public void setContractorName(String value) {
        setAttributeInternal(CONTRACTORNAME, value);
    }

    /**
     * Gets the attribute value for TotalPly, using the alias name TotalPly.
     * @return the TotalPly
     */
    public Number getTotalPly() {
        return (Number)getAttributeInternal(TOTALPLY);
    }

    /**
     * Sets <code>value</code> as the attribute value for TotalPly.
     * @param value value to set the TotalPly
     */
    public void setTotalPly(Number value) {
        setAttributeInternal(TOTALPLY, value);
    }

    /**
     * Gets the attribute value for TotalPlyRej, using the alias name TotalPlyRej.
     * @return the TotalPlyRej
     */
    public Number getTotalPlyRej() {
        return (Number)getAttributeInternal(TOTALPLYREJ);
    }

    /**
     * Sets <code>value</code> as the attribute value for TotalPlyRej.
     * @param value value to set the TotalPlyRej
     */
    public void setTotalPlyRej(Number value) {
        setAttributeInternal(TOTALPLYREJ, value);
    }

    /**
     * Gets the attribute value for TotalRatio, using the alias name TotalRatio.
     * @return the TotalRatio
     */
    public Number getTotalRatio() {
        return (Number)getAttributeInternal(TOTALRATIO);
    }

    /**
     * Sets <code>value</code> as the attribute value for TotalRatio.
     * @param value value to set the TotalRatio
     */
    public void setTotalRatio(Number value) {
        setAttributeInternal(TOTALRATIO, value);
    }

    /**
     * Gets the attribute value for FabricWidth, using the alias name FabricWidth.
     * @return the FabricWidth
     */
    public Number getFabricWidth() {
        return (Number)getAttributeInternal(FABRICWIDTH);
    }

    /**
     * Sets <code>value</code> as the attribute value for FabricWidth.
     * @param value value to set the FabricWidth
     */
    public void setFabricWidth(Number value) {
        setAttributeInternal(FABRICWIDTH, value);
    }

    /**
     * Gets the attribute value for FabricPattern, using the alias name FabricPattern.
     * @return the FabricPattern
     */
    public String getFabricPattern() {
        return (String)getAttributeInternal(FABRICPATTERN);
    }

    /**
     * Sets <code>value</code> as the attribute value for FabricPattern.
     * @param value value to set the FabricPattern
     */
    public void setFabricPattern(String value) {
        setAttributeInternal(FABRICPATTERN, value);
    }

    /**
     * Gets the attribute value for MarkerLength, using the alias name MarkerLength.
     * @return the MarkerLength
     */
    public Number getMarkerLength() {
        return (Number)getAttributeInternal(MARKERLENGTH);
    }

    /**
     * Sets <code>value</code> as the attribute value for MarkerLength.
     * @param value value to set the MarkerLength
     */
    public void setMarkerLength(Number value) {
        setAttributeInternal(MARKERLENGTH, value);
    }

    /**
     * Gets the attribute value for CF, using the alias name CF.
     * @return the CF
     */
    public Number getCF() {
        return (Number)getAttributeInternal(CF);
    }

    /**
     * Sets <code>value</code> as the attribute value for CF.
     * @param value value to set the CF
     */
    public void setCF(Number value) {
        setAttributeInternal(CF, value);
    }

    /**
     * Gets the attribute value for ExtraMtr, using the alias name ExtraMtr.
     * @return the ExtraMtr
     */
    public Number getExtraMtr() {
        return (Number)getAttributeInternal(EXTRAMTR);
    }

    /**
     * Sets <code>value</code> as the attribute value for ExtraMtr.
     * @param value value to set the ExtraMtr
     */
    public void setExtraMtr(Number value) {
        setAttributeInternal(EXTRAMTR, value);
    }

    /**
     * Gets the attribute value for PostedStatus, using the alias name PostedStatus.
     * @return the PostedStatus
     */
    public String getPostedStatus() {
        return (String)getAttributeInternal(POSTEDSTATUS);
    }

    /**
     * Sets <code>value</code> as the attribute value for PostedStatus.
     * @param value value to set the PostedStatus
     */
    public void setPostedStatus(String value) {
        setAttributeInternal(POSTEDSTATUS, value);
    }

    /**
     * Gets the attribute value for PostedDate, using the alias name PostedDate.
     * @return the PostedDate
     */
    public Date getPostedDate() {
        return (Date)getAttributeInternal(POSTEDDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for PostedDate.
     * @param value value to set the PostedDate
     */
    public void setPostedDate(Date value) {
        setAttributeInternal(POSTEDDATE, value);
    }

    /**
     * Gets the attribute value for SprConTypeId, using the alias name SprConTypeId.
     * @return the SprConTypeId
     */
    public String getSprConTypeId() {
        return (String)getAttributeInternal(SPRCONTYPEID);
    }

    /**
     * Sets <code>value</code> as the attribute value for SprConTypeId.
     * @param value value to set the SprConTypeId
     */
    public void setSprConTypeId(String value) {
        setAttributeInternal(SPRCONTYPEID, value);
    }

    /**
     * Gets the attribute value for SprContractorId, using the alias name SprContractorId.
     * @return the SprContractorId
     */
    public String getSprContractorId() {
        return (String)getAttributeInternal(SPRCONTRACTORID);
    }

    /**
     * Sets <code>value</code> as the attribute value for SprContractorId.
     * @param value value to set the SprContractorId
     */
    public void setSprContractorId(String value) {
        setAttributeInternal(SPRCONTRACTORID, value);
    }

    /**
     * Gets the attribute value for CutConTypeId, using the alias name CutConTypeId.
     * @return the CutConTypeId
     */
    public String getCutConTypeId() {
        return (String)getAttributeInternal(CUTCONTYPEID);
    }

    /**
     * Sets <code>value</code> as the attribute value for CutConTypeId.
     * @param value value to set the CutConTypeId
     */
    public void setCutConTypeId(String value) {
        setAttributeInternal(CUTCONTYPEID, value);
    }

    /**
     * Gets the attribute value for CutContractorId, using the alias name CutContractorId.
     * @return the CutContractorId
     */
    public String getCutContractorId() {
        return (String)getAttributeInternal(CUTCONTRACTORID);
    }

    /**
     * Sets <code>value</code> as the attribute value for CutContractorId.
     * @param value value to set the CutContractorId
     */
    public void setCutContractorId(String value) {
        setAttributeInternal(CUTCONTRACTORID, value);
    }

    /**
     * Gets the attribute value for NumConTypeId, using the alias name NumConTypeId.
     * @return the NumConTypeId
     */
    public String getNumConTypeId() {
        return (String)getAttributeInternal(NUMCONTYPEID);
    }

    /**
     * Sets <code>value</code> as the attribute value for NumConTypeId.
     * @param value value to set the NumConTypeId
     */
    public void setNumConTypeId(String value) {
        setAttributeInternal(NUMCONTYPEID, value);
    }

    /**
     * Gets the attribute value for NumContractorId, using the alias name NumContractorId.
     * @return the NumContractorId
     */
    public String getNumContractorId() {
        return (String)getAttributeInternal(NUMCONTRACTORID);
    }

    /**
     * Sets <code>value</code> as the attribute value for NumContractorId.
     * @param value value to set the NumContractorId
     */
    public void setNumContractorId(String value) {
        setAttributeInternal(NUMCONTRACTORID, value);
    }

    /**
     * Gets the attribute value for FabricType, using the alias name FabricType.
     * @return the FabricType
     */
    public String getFabricType() {
        return (String)getAttributeInternal(FABRICTYPE);
    }

    /**
     * Sets <code>value</code> as the attribute value for FabricType.
     * @param value value to set the FabricType
     */
    public void setFabricType(String value) {
        setAttributeInternal(FABRICTYPE, value);
    }

    /**
     * Gets the attribute value for Paymentlock, using the alias name Paymentlock.
     * @return the Paymentlock
     */
    public String getPaymentlock() {
        return (String)getAttributeInternal(PAYMENTLOCK);
    }

    /**
     * Sets <code>value</code> as the attribute value for Paymentlock.
     * @param value value to set the Paymentlock
     */
    public void setPaymentlock(String value) {
        setAttributeInternal(PAYMENTLOCK, value);
    }

    /**
     * Gets the attribute value for LastUpdateDate, using the alias name LastUpdateDate.
     * @return the LastUpdateDate
     */
    public Date getLastUpdateDate() {
        return (Date)getAttributeInternal(LASTUPDATEDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for LastUpdateDate.
     * @param value value to set the LastUpdateDate
     */
    public void setLastUpdateDate(Date value) {
        setAttributeInternal(LASTUPDATEDATE, value);
    }

    /**
     * Gets the attribute value for LastUpdatedBy, using the alias name LastUpdatedBy.
     * @return the LastUpdatedBy
     */
    public Number getLastUpdatedBy() {
        return (Number)getAttributeInternal(LASTUPDATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for LastUpdatedBy.
     * @param value value to set the LastUpdatedBy
     */
    public void setLastUpdatedBy(Number value) {
        setAttributeInternal(LASTUPDATEDBY, value);
    }

    /**
     * Gets the attribute value for CreationDate, using the alias name CreationDate.
     * @return the CreationDate
     */
    public Date getCreationDate() {
        return (Date)getAttributeInternal(CREATIONDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreationDate.
     * @param value value to set the CreationDate
     */
    public void setCreationDate(Date value) {
        setAttributeInternal(CREATIONDATE, value);
    }

    /**
     * Gets the attribute value for CreatedBy, using the alias name CreatedBy.
     * @return the CreatedBy
     */
    public Number getCreatedBy() {
        return (Number)getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreatedBy.
     * @param value value to set the CreatedBy
     */
    public void setCreatedBy(Number value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for PrrangeDate, using the alias name PrrangeDate.
     * @return the PrrangeDate
     */
    public Date getPrrangeDate() {
        return (Date)getAttributeInternal(PRRANGEDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for PrrangeDate.
     * @param value value to set the PrrangeDate
     */
    public void setPrrangeDate(Date value) {
        setAttributeInternal(PRRANGEDATE, value);
    }

    /**
     * Gets the attribute value for CuttingDate, using the alias name CuttingDate.
     * @return the CuttingDate
     */
    public Date getCuttingDate() {
        return (Date)getAttributeInternal(CUTTINGDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for CuttingDate.
     * @param value value to set the CuttingDate
     */
    public void setCuttingDate(Date value) {
        setAttributeInternal(CUTTINGDATE, value);
    }

    /**
     * Gets the attribute value for NumberingDate, using the alias name NumberingDate.
     * @return the NumberingDate
     */
    public Date getNumberingDate() {
        return (Date)getAttributeInternal(NUMBERINGDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for NumberingDate.
     * @param value value to set the NumberingDate
     */
    public void setNumberingDate(Date value) {
        setAttributeInternal(NUMBERINGDATE, value);
    }

    /**
     * Gets the attribute value for RangePosted, using the alias name RangePosted.
     * @return the RangePosted
     */
    public String getRangePosted() {
        return (String)getAttributeInternal(RANGEPOSTED);
    }

    /**
     * Sets <code>value</code> as the attribute value for RangePosted.
     * @param value value to set the RangePosted
     */
    public void setRangePosted(String value) {
        setAttributeInternal(RANGEPOSTED, value);
    }

    /**
     * Gets the attribute value for CuttPosted, using the alias name CuttPosted.
     * @return the CuttPosted
     */
    public String getCuttPosted() {
        return (String)getAttributeInternal(CUTTPOSTED);
    }

    /**
     * Sets <code>value</code> as the attribute value for CuttPosted.
     * @param value value to set the CuttPosted
     */
    public void setCuttPosted(String value) {
        setAttributeInternal(CUTTPOSTED, value);
    }

    /**
     * Gets the attribute value for NumPosted, using the alias name NumPosted.
     * @return the NumPosted
     */
    public String getNumPosted() {
        return (String)getAttributeInternal(NUMPOSTED);
    }

    /**
     * Sets <code>value</code> as the attribute value for NumPosted.
     * @param value value to set the NumPosted
     */
    public void setNumPosted(String value) {
        setAttributeInternal(NUMPOSTED, value);
    }

    /**
     * Gets the attribute value for InspDate, using the alias name InspDate.
     * @return the InspDate
     */
    public Date getInspDate() {
        return (Date)getAttributeInternal(INSPDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for InspDate.
     * @param value value to set the InspDate
     */
    public void setInspDate(Date value) {
        setAttributeInternal(INSPDATE, value);
    }

    /**
     * Gets the attribute value for InspRemarks, using the alias name InspRemarks.
     * @return the InspRemarks
     */
    public String getInspRemarks() {
        return (String)getAttributeInternal(INSPREMARKS);
    }

    /**
     * Sets <code>value</code> as the attribute value for InspRemarks.
     * @param value value to set the InspRemarks
     */
    public void setInspRemarks(String value) {
        setAttributeInternal(INSPREMARKS, value);
    }

    /**
     * Gets the attribute value for IssueStatus, using the alias name IssueStatus.
     * @return the IssueStatus
     */
    public String getIssueStatus() {
        return (String)getAttributeInternal(ISSUESTATUS);
    }

    /**
     * Sets <code>value</code> as the attribute value for IssueStatus.
     * @param value value to set the IssueStatus
     */
    public void setIssueStatus(String value) {
        setAttributeInternal(ISSUESTATUS, value);
    }

    /**
     * Gets the attribute value for CompleteStatus, using the alias name CompleteStatus.
     * @return the CompleteStatus
     */
    public String getCompleteStatus() {
        return (String)getAttributeInternal(COMPLETESTATUS);
    }

    /**
     * Sets <code>value</code> as the attribute value for CompleteStatus.
     * @param value value to set the CompleteStatus
     */
    public void setCompleteStatus(String value) {
        setAttributeInternal(COMPLETESTATUS, value);
    }

    /**
     * Gets the attribute value for Subinventory, using the alias name Subinventory.
     * @return the Subinventory
     */
    public String getSubinventory() {
        return (String)getAttributeInternal(SUBINVENTORY);
    }

    /**
     * Sets <code>value</code> as the attribute value for Subinventory.
     * @param value value to set the Subinventory
     */
    public void setSubinventory(String value) {
        setAttributeInternal(SUBINVENTORY, value);
    }

    /**
     * Gets the attribute value for VrfyPost, using the alias name VrfyPost.
     * @return the VrfyPost
     */
    public String getVrfyPost() {
        return (String)getAttributeInternal(VRFYPOST);
    }

    /**
     * Sets <code>value</code> as the attribute value for VrfyPost.
     * @param value value to set the VrfyPost
     */
    public void setVrfyPost(String value) {
        setAttributeInternal(VRFYPOST, value);
    }

    /**
     * Gets the attribute value for CuttPostedTmp, using the alias name CuttPostedTmp.
     * @return the CuttPostedTmp
     */
    public String getCuttPostedTmp() {
        return (String)getAttributeInternal(CUTTPOSTEDTMP);
    }

    /**
     * Sets <code>value</code> as the attribute value for CuttPostedTmp.
     * @param value value to set the CuttPostedTmp
     */
    public void setCuttPostedTmp(String value) {
        setAttributeInternal(CUTTPOSTEDTMP, value);
    }

    /**
     * Gets the attribute value for NumPostedTmp, using the alias name NumPostedTmp.
     * @return the NumPostedTmp
     */
    public String getNumPostedTmp() {
        return (String)getAttributeInternal(NUMPOSTEDTMP);
    }

    /**
     * Sets <code>value</code> as the attribute value for NumPostedTmp.
     * @param value value to set the NumPostedTmp
     */
    public void setNumPostedTmp(String value) {
        setAttributeInternal(NUMPOSTEDTMP, value);
    }

    /**
     * Gets the attribute value for RangePostedTmp, using the alias name RangePostedTmp.
     * @return the RangePostedTmp
     */
    public String getRangePostedTmp() {
        return (String)getAttributeInternal(RANGEPOSTEDTMP);
    }

    /**
     * Sets <code>value</code> as the attribute value for RangePostedTmp.
     * @param value value to set the RangePostedTmp
     */
    public void setRangePostedTmp(String value) {
        setAttributeInternal(RANGEPOSTEDTMP, value);
    }

    /**
     * Gets the attribute value for CompleteStatusTmp, using the alias name CompleteStatusTmp.
     * @return the CompleteStatusTmp
     */
    public String getCompleteStatusTmp() {
        return (String)getAttributeInternal(COMPLETESTATUSTMP);
    }

    /**
     * Sets <code>value</code> as the attribute value for CompleteStatusTmp.
     * @param value value to set the CompleteStatusTmp
     */
    public void setCompleteStatusTmp(String value) {
        setAttributeInternal(COMPLETESTATUSTMP, value);
    }

    /**
     * Gets the attribute value for CutInchargeId, using the alias name CutInchargeId.
     * @return the CutInchargeId
     */
    public String getCutInchargeId() {
        return (String)getAttributeInternal(CUTINCHARGEID);
    }

    /**
     * Sets <code>value</code> as the attribute value for CutInchargeId.
     * @param value value to set the CutInchargeId
     */
    public void setCutInchargeId(String value) {
        setAttributeInternal(CUTINCHARGEID, value);
    }

    /**
     * Gets the attribute value for NumStatus, using the alias name NumStatus.
     * @return the NumStatus
     */
    public String getNumStatus() {
        return (String)getAttributeInternal(NUMSTATUS);
    }

    /**
     * Sets <code>value</code> as the attribute value for NumStatus.
     * @param value value to set the NumStatus
     */
    public void setNumStatus(String value) {
        setAttributeInternal(NUMSTATUS, value);
    }

    /**
     * Gets the attribute value for LastUpdateLogin, using the alias name LastUpdateLogin.
     * @return the LastUpdateLogin
     */
    public Number getLastUpdateLogin() {
        return (Number)getAttributeInternal(LASTUPDATELOGIN);
    }

    /**
     * Sets <code>value</code> as the attribute value for LastUpdateLogin.
     * @param value value to set the LastUpdateLogin
     */
    public void setLastUpdateLogin(Number value) {
        setAttributeInternal(LASTUPDATELOGIN, value);
    }

    /**
     * Gets the attribute value for Attribute1, using the alias name Attribute1.
     * @return the Attribute1
     */
    public String getAttribute1() {
        return (String)getAttributeInternal(ATTRIBUTE1);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute1.
     * @param value value to set the Attribute1
     */
    public void setAttribute1(String value) {
        setAttributeInternal(ATTRIBUTE1, value);
    }

    /**
     * Gets the attribute value for Attribute2, using the alias name Attribute2.
     * @return the Attribute2
     */
    public String getAttribute2() {
        return (String)getAttributeInternal(ATTRIBUTE2);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute2.
     * @param value value to set the Attribute2
     */
    public void setAttribute2(String value) {
        setAttributeInternal(ATTRIBUTE2, value);
    }

    /**
     * Gets the attribute value for Attribute3, using the alias name Attribute3.
     * @return the Attribute3
     */
    public String getAttribute3() {
        return (String)getAttributeInternal(ATTRIBUTE3);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute3.
     * @param value value to set the Attribute3
     */
    public void setAttribute3(String value) {
        setAttributeInternal(ATTRIBUTE3, value);
    }

    /**
     * Gets the attribute value for Attribute4, using the alias name Attribute4.
     * @return the Attribute4
     */
    public String getAttribute4() {
        return (String)getAttributeInternal(ATTRIBUTE4);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute4.
     * @param value value to set the Attribute4
     */
    public void setAttribute4(String value) {
        setAttributeInternal(ATTRIBUTE4, value);
    }

    /**
     * Gets the attribute value for Attribute5, using the alias name Attribute5.
     * @return the Attribute5
     */
    public String getAttribute5() {
        return (String)getAttributeInternal(ATTRIBUTE5);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute5.
     * @param value value to set the Attribute5
     */
    public void setAttribute5(String value) {
        setAttributeInternal(ATTRIBUTE5, value);
    }

    /**
     * Gets the attribute value for Attribute6, using the alias name Attribute6.
     * @return the Attribute6
     */
    public String getAttribute6() {
        return (String)getAttributeInternal(ATTRIBUTE6);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute6.
     * @param value value to set the Attribute6
     */
    public void setAttribute6(String value) {
        setAttributeInternal(ATTRIBUTE6, value);
    }

    /**
     * Gets the attribute value for Attribute7, using the alias name Attribute7.
     * @return the Attribute7
     */
    public String getAttribute7() {
        return (String)getAttributeInternal(ATTRIBUTE7);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute7.
     * @param value value to set the Attribute7
     */
    public void setAttribute7(String value) {
        setAttributeInternal(ATTRIBUTE7, value);
    }

    /**
     * Gets the attribute value for Attribute8, using the alias name Attribute8.
     * @return the Attribute8
     */
    public String getAttribute8() {
        return (String)getAttributeInternal(ATTRIBUTE8);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute8.
     * @param value value to set the Attribute8
     */
    public void setAttribute8(String value) {
        setAttributeInternal(ATTRIBUTE8, value);
    }

    /**
     * Gets the attribute value for Attribute9, using the alias name Attribute9.
     * @return the Attribute9
     */
    public String getAttribute9() {
        return (String)getAttributeInternal(ATTRIBUTE9);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute9.
     * @param value value to set the Attribute9
     */
    public void setAttribute9(String value) {
        setAttributeInternal(ATTRIBUTE9, value);
    }

    /**
     * Gets the attribute value for Attribute10, using the alias name Attribute10.
     * @return the Attribute10
     */
    public String getAttribute10() {
        return (String)getAttributeInternal(ATTRIBUTE10);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute10.
     * @param value value to set the Attribute10
     */
    public void setAttribute10(String value) {
        setAttributeInternal(ATTRIBUTE10, value);
    }

    /**
     * Gets the attribute value for Attribute11, using the alias name Attribute11.
     * @return the Attribute11
     */
    public String getAttribute11() {
        return (String)getAttributeInternal(ATTRIBUTE11);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute11.
     * @param value value to set the Attribute11
     */
    public void setAttribute11(String value) {
        setAttributeInternal(ATTRIBUTE11, value);
    }

    /**
     * Gets the attribute value for Attribute12, using the alias name Attribute12.
     * @return the Attribute12
     */
    public String getAttribute12() {
        return (String)getAttributeInternal(ATTRIBUTE12);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute12.
     * @param value value to set the Attribute12
     */
    public void setAttribute12(String value) {
        setAttributeInternal(ATTRIBUTE12, value);
    }

    /**
     * Gets the attribute value for Attribute13, using the alias name Attribute13.
     * @return the Attribute13
     */
    public String getAttribute13() {
        return (String)getAttributeInternal(ATTRIBUTE13);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute13.
     * @param value value to set the Attribute13
     */
    public void setAttribute13(String value) {
        setAttributeInternal(ATTRIBUTE13, value);
    }

    /**
     * Gets the attribute value for Attribute14, using the alias name Attribute14.
     * @return the Attribute14
     */
    public String getAttribute14() {
        return (String)getAttributeInternal(ATTRIBUTE14);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute14.
     * @param value value to set the Attribute14
     */
    public void setAttribute14(String value) {
        setAttributeInternal(ATTRIBUTE14, value);
    }

    /**
     * Gets the attribute value for Attribute15, using the alias name Attribute15.
     * @return the Attribute15
     */
    public String getAttribute15() {
        return (String)getAttributeInternal(ATTRIBUTE15);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute15.
     * @param value value to set the Attribute15
     */
    public void setAttribute15(String value) {
        setAttributeInternal(ATTRIBUTE15, value);
    }

    /**
     * Gets the attribute value for BuyerId, using the alias name BuyerId.
     * @return the BuyerId
     */
    public Number getBuyerId() {
        return (Number)getAttributeInternal(BUYERID);
    }

    /**
     * Sets <code>value</code> as the attribute value for BuyerId.
     * @param value value to set the BuyerId
     */
    public void setBuyerId(Number value) {
        setAttributeInternal(BUYERID, value);
    }

    /**
     * Gets the attribute value for Style, using the alias name Style.
     * @return the Style
     */
    public String getStyle() {
        return (String)getAttributeInternal(STYLE);
    }

    /**
     * Sets <code>value</code> as the attribute value for Style.
     * @param value value to set the Style
     */
    public void setStyle(String value) {
        setAttributeInternal(STYLE, value);
    }

    /**
     * Gets the attribute value for OrderQty, using the alias name OrderQty.
     * @return the OrderQty
     */
    public Number getOrderQty() {
        return (Number)getAttributeInternal(ORDERQTY);
    }

    /**
     * Sets <code>value</code> as the attribute value for OrderQty.
     * @param value value to set the OrderQty
     */
    public void setOrderQty(Number value) {
        setAttributeInternal(ORDERQTY, value);
    }

    /**
     * Gets the attribute value for Stn, using the alias name Stn.
     * @return the Stn
     */
    public String getStn() {
        return (String)getAttributeInternal(STN);
    }

    /**
     * Sets <code>value</code> as the attribute value for Stn.
     * @param value value to set the Stn
     */
    public void setStn(String value) {
        setAttributeInternal(STN, value);
    }

    /**
     * Gets the attribute value for BpoNo, using the alias name BpoNo.
     * @return the BpoNo
     */
    public String getBpoNo() {
        return (String)getAttributeInternal(BPONO);
    }

    /**
     * Sets <code>value</code> as the attribute value for BpoNo.
     * @param value value to set the BpoNo
     */
    public void setBpoNo(String value) {
        setAttributeInternal(BPONO, value);
    }

    /**
     * Gets the attribute value for Season, using the alias name Season.
     * @return the Season
     */
    public String getSeason() {
        return (String)getAttributeInternal(SEASON);
    }

    /**
     * Sets <code>value</code> as the attribute value for Season.
     * @param value value to set the Season
     */
    public void setSeason(String value) {
        setAttributeInternal(SEASON, value);
    }

    /**
     * Gets the attribute value for PocId, using the alias name PocId.
     * @return the PocId
     */
    public Number getPocId() {
        return (Number)getAttributeInternal(POCID);
    }

    /**
     * Sets <code>value</code> as the attribute value for PocId.
     * @param value value to set the PocId
     */
    public void setPocId(Number value) {
        setAttributeInternal(POCID, value);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }

    /**
     * @return the associated entity oracle.jbo.RowIterator.
     */
    public RowIterator getLineEO() {
        return (RowIterator)getAttributeInternal(LINEEO);
    }


    /**
     * @return the associated entity DetailEOImpl.
     */
    public DetailEOImpl getDetailEO() {
        return (DetailEOImpl)getAttributeInternal(DETAILEO);
    }

    /**
     * Sets <code>value</code> as the associated entity DetailEOImpl.
     */
    public void setDetailEO(DetailEOImpl value) {
        setAttributeInternal(DETAILEO, value);
    }


    /**
     * @param rangeId key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(Number rangeId) {
        return new Key(new Object[]{rangeId});
    }

    /**
     * Add attribute defaulting logic in this method.
     * @param attributeList list of attribute names/values to initialize the row
     */
    protected void create(AttributeList attributeList) {
        super.create(attributeList);
        Integer empno =Integer.parseInt(new oracle.jbo.server.SequenceImpl("MNJ_MFG_RANGEPROGRAM_s", getDBTransaction()).getSequenceNumber().toString());
           oracle.jbo.server.SequenceImpl s =new oracle.jbo.server.SequenceImpl("MNJ_MFG_RANGEPROGRAM_s",getDBTransaction());
           oracle.jbo.domain.Number sVal = s.getSequenceNumber();
           setRangeId(sVal);
           //cust_mnj_ont_pkg.cust_mnj_packassort_srno
       
    }
    
    public int getSrNoString() {
          int srno = 0;
          String stmt = "BEGIN :1 := mnj_mfg_doc_no_pkg.cut_prod_srno; end;";
          java.sql.CallableStatement cs =   getDBTransaction().createCallableStatement(stmt, 1);
          try {
              cs.registerOutParameter(1, oracle.jdbc.OracleTypes.VARCHAR);
              cs.execute();
              srno = cs.getInt(1);
              cs.close();
          } catch (Exception e) {
              e.printStackTrace();
          }
          return srno;
    }

    /**
     * Add entity remove logic in this method.
     */
    public void remove() {
        super.remove();
    }

    /**
     * Add locking logic here.
     */
    public void lock() {
        super.lock();
    }

    /**
     * Custom DML update/insert/delete logic here.
     * @param operation the operation type
     * @param e the transaction event
     */
    
    //---------------Method in EO -----------------------------------------------
        protected void doDML(int operation, TransactionEvent e) {
           
            Map sessionScope = ADFContext.getCurrent().getSessionScope();   
            String user = (String)sessionScope.get("userId");   
            String OrgId = (String)sessionScope.get("orgId");
           
            if(DML_UPDATE == operation){
                try {
                    setLastUpdateDate((Date)Date.getCurrentDate()); 
                    setLastUpdatedBy(new oracle.jbo.domain.Number(user));
                    setDivisionId(OrgId); 
                } catch (SQLException f) {
                    System.out.println(f.getMessage());
                }
            }
            else if (DML_INSERT == operation){
             
                try {
                    System.out.println("Document No -->"+getSrNoString());
                    
                    setRangeNumber(new oracle.jbo.domain.Number(getSrNoString())); 
                    setCreationDate((Date)Date.getCurrentDate());  
                    setCreatedBy(new oracle.jbo.domain.Number(user));
                    setDivisionId(OrgId); 
                   
                   
                } catch (SQLException f) {
                    ;
                }
            }
            super.doDML(operation, e);
        }
    
    
    
}
